In [208]:
import numpy as np

# Banking dataset
banking_data = np.array([
    [101, 5000, 720, 25, 5],
    [102, 12000, 810, 40, 10],
    [103, 3000, 650, 18, 3],
    [104, 8500, 770, 30, 7],
    [105, 2000, 600, 12, 2],
    [106, 15000, 850, 50, 12],
    [107, 4500, 690, 22, 4],
    [108, 9800, 780, 35, 8],
    [109, 2500, 620, 15, 3],
    [110, 11000, 800, 38, 9]
])

print(banking_data)

[[  101  5000   720    25     5]
 [  102 12000   810    40    10]
 [  103  3000   650    18     3]
 [  104  8500   770    30     7]
 [  105  2000   600    12     2]
 [  106 15000   850    50    12]
 [  107  4500   690    22     4]
 [  108  9800   780    35     8]
 [  109  2500   620    15     3]
 [  110 11000   800    38     9]]


In [209]:
#Create a 4x4 identity matrix using np.eye()
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [210]:
#Create an array of 8 zeros using np.zeros()
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [211]:
#Create an array of 6 ones using np.ones()
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [212]:
#Create an array with values from 0 to 15 using np.arange()
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [213]:
#Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
np.linspace(1,100,8)

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

#### Array Attributes and Information

In [214]:
#What is the shape of the banking_data array?
banking_data.shape

(10, 5)

In [215]:
# What is the data type of the banking_data array?
banking_data.dtype

dtype('int64')

In [216]:
# What is the size (total number of elements) of the banking_data array?
banking_data.size

50

In [217]:
# What is the number of dimensions of the banking_data array?
banking_data.ndim

2

In [218]:
# What is the memory size of the banking_data array in bytes?
banking_data.nbytes

400

#### Indexing and Slicing

In [219]:
# Extract the first row of banking_data
banking_data[0]

array([ 101, 5000,  720,   25,    5])

In [220]:
#  Extract the last row of banking_data
banking_data[-1]

array([  110, 11000,   800,    38,     9])

In [221]:
# Extract the Account_Balance column (column index 1)
banking_data[:,1]

array([ 5000, 12000,  3000,  8500,  2000, 15000,  4500,  9800,  2500,
       11000])

In [222]:
# Extract the first 4 rows and first 3 columns
banking_data[:4,:3]

array([[  101,  5000,   720],
       [  102, 12000,   810],
       [  103,  3000,   650],
       [  104,  8500,   770]])

In [223]:
# Extract rows 3 to 7 (inclusive)
banking_data[3:8]

array([[  104,  8500,   770,    30,     7],
       [  105,  2000,   600,    12,     2],
       [  106, 15000,   850,    50,    12],
       [  107,  4500,   690,    22,     4],
       [  108,  9800,   780,    35,     8]])

#### Mathematical Operations


In [224]:
# Calculate the sum of all account balances
np.sum(banking_data[:,1])

np.int64(73300)

In [225]:
# Calculate the mean account balance
np.mean(banking_data[:,1])

np.float64(7330.0)

In [226]:
#Calculate the standard deviation of account balances
np.std(banking_data[:,1])



np.float64(4306.982702542466)

In [227]:
#Calculate the variance of account balance
np.var(banking_data[:,1])

np.float64(18550100.0)

In [228]:
#Calculate the median account balance
np.median(banking_data[:,1])

np.float64(6750.0)

## Statistical Functions

In [229]:
#Find the minimum and maximum account balances
min_account_balance = np.min(banking_data[:,1])
max_account_balance = np.max(banking_data[:,1])
print(f"minimum : {min_account_balance}")
print(f"maximum : {max_account_balance}")

minimum : 2000
maximum : 15000


In [230]:
# Find the minimum and maximum credit scores
min_credit_score = np.min(banking_data[:,2])
print(f"minimum credit score :{min_credit_score}")

minimum credit score :600


In [231]:
#  Calculate the percentile values for account balances (25th, 50th, 75th)
percentiles = np.percentile(banking_data[:,1], [25, 50, 75])
print(percentiles)

[ 3375.  6750. 10700.]


In [232]:
# Calculate the correlation between account balance and credit score
np.corrcoef(banking_data[:,1],banking_data[:,2])

array([[1.        , 0.97325153],
       [0.97325153, 1.        ]])

In [233]:
# Calculate the covariance between account balance and credit score
np.cov(banking_data[:,1],banking_data[:,2])

array([[2.06112222e+07, 3.80922222e+05],
       [3.80922222e+05, 7.43222222e+03]])

### Array Reshaping and Manipulation

In [234]:
#  Reshape the banking_data to 5 rows × 10 columns
np.reshape(banking_data,(5,10))

array([[  101,  5000,   720,    25,     5,   102, 12000,   810,    40,
           10],
       [  103,  3000,   650,    18,     3,   104,  8500,   770,    30,
            7],
       [  105,  2000,   600,    12,     2,   106, 15000,   850,    50,
           12],
       [  107,  4500,   690,    22,     4,   108,  9800,   780,    35,
            8],
       [  109,  2500,   620,    15,     3,   110, 11000,   800,    38,
            9]])

In [235]:
# Flatten the banking_data to a 1D array
banking_data.flatten()

array([  101,  5000,   720,    25,     5,   102, 12000,   810,    40,
          10,   103,  3000,   650,    18,     3,   104,  8500,   770,
          30,     7,   105,  2000,   600,    12,     2,   106, 15000,
         850,    50,    12,   107,  4500,   690,    22,     4,   108,
        9800,   780,    35,     8,   109,  2500,   620,    15,     3,
         110, 11000,   800,    38,     9])

In [236]:
# Transpose the banking_data
banking_data.T

array([[  101,   102,   103,   104,   105,   106,   107,   108,   109,
          110],
       [ 5000, 12000,  3000,  8500,  2000, 15000,  4500,  9800,  2500,
        11000],
       [  720,   810,   650,   770,   600,   850,   690,   780,   620,
          800],
       [   25,    40,    18,    30,    12,    50,    22,    35,    15,
           38],
       [    5,    10,     3,     7,     2,    12,     4,     8,     3,
            9]])

In [237]:
#Split the banking_data into 2 equal parts vertically
np.vsplit(banking_data,2)

[array([[  101,  5000,   720,    25,     5],
        [  102, 12000,   810,    40,    10],
        [  103,  3000,   650,    18,     3],
        [  104,  8500,   770,    30,     7],
        [  105,  2000,   600,    12,     2]]),
 array([[  106, 15000,   850,    50,    12],
        [  107,  4500,   690,    22,     4],
        [  108,  9800,   780,    35,     8],
        [  109,  2500,   620,    15,     3],
        [  110, 11000,   800,    38,     9]])]

In [238]:
# Split the banking_data into 2 equal parts horizontally
np.hsplit(banking_data,5)

[array([[101],
        [102],
        [103],
        [104],
        [105],
        [106],
        [107],
        [108],
        [109],
        [110]]),
 array([[ 5000],
        [12000],
        [ 3000],
        [ 8500],
        [ 2000],
        [15000],
        [ 4500],
        [ 9800],
        [ 2500],
        [11000]]),
 array([[720],
        [810],
        [650],
        [770],
        [600],
        [850],
        [690],
        [780],
        [620],
        [800]]),
 array([[25],
        [40],
        [18],
        [30],
        [12],
        [50],
        [22],
        [35],
        [15],
        [38]]),
 array([[ 5],
        [10],
        [ 3],
        [ 7],
        [ 2],
        [12],
        [ 4],
        [ 8],
        [ 3],
        [ 9]])]

#### Logical Operations and Filtering

In [239]:
#Find customers with account balance greater than $100,000
banking_data[banking_data[:,1] > 100000]

array([], shape=(0, 5), dtype=int64)

In [240]:
# Find customers with credit score greater than 800
banking_data[banking_data[:,2]>800]

array([[  102, 12000,   810,    40,    10],
       [  106, 15000,   850,    50,    12]])

In [241]:
# Find customers with transaction count greater than 50 AND credit score less than 750
banking_data[(banking_data[:,3] > 50) & (banking_data[:,2] < 750)]

array([], shape=(0, 5), dtype=int64)

In [242]:
# Count how many customers have account balance between $10,000 and $100,000
np.sum((banking_data[:,1] >= 10000) & (banking_data[:,1] <= 100000))

np.int64(3)

In [243]:
# Find the index of the customer with the highest credit score
np.argmax(banking_data[:,2])

np.int64(5)

### Sorting and Searching

In [244]:
# Sort the banking_data by account balance (ascending)
banking_data[np.argsort(banking_data[:,1])]


array([[  105,  2000,   600,    12,     2],
       [  109,  2500,   620,    15,     3],
       [  103,  3000,   650,    18,     3],
       [  107,  4500,   690,    22,     4],
       [  101,  5000,   720,    25,     5],
       [  104,  8500,   770,    30,     7],
       [  108,  9800,   780,    35,     8],
       [  110, 11000,   800,    38,     9],
       [  102, 12000,   810,    40,    10],
       [  106, 15000,   850,    50,    12]])

In [245]:
# Sort the banking_data by credit score (descending)
banking_data[np.argsort(banking_data[:,2])[::-1]]

array([[  106, 15000,   850,    50,    12],
       [  102, 12000,   810,    40,    10],
       [  110, 11000,   800,    38,     9],
       [  108,  9800,   780,    35,     8],
       [  104,  8500,   770,    30,     7],
       [  101,  5000,   720,    25,     5],
       [  107,  4500,   690,    22,     4],
       [  103,  3000,   650,    18,     3],
       [  109,  2500,   620,    15,     3],
       [  105,  2000,   600,    12,     2]])

In [246]:
# Find the indices that would sort the array by years active
np.argsort(banking_data[:,4])


array([4, 2, 8, 6, 0, 3, 7, 9, 1, 5])

In [247]:
# Find the customer with the second highest account balance

banking_data[np.argsort(banking_data[:,1])[-2]]

array([  102, 12000,   810,    40,    10])

In [248]:
# Find the customer with the lowest transaction count
banking_data[np.argmin(banking_data[:,3])]

array([ 105, 2000,  600,   12,    2])

In [249]:
# Q9.1: Calculate the absolute values of all elements
np.abs(banking_data)

array([[  101,  5000,   720,    25,     5],
       [  102, 12000,   810,    40,    10],
       [  103,  3000,   650,    18,     3],
       [  104,  8500,   770,    30,     7],
       [  105,  2000,   600,    12,     2],
       [  106, 15000,   850,    50,    12],
       [  107,  4500,   690,    22,     4],
       [  108,  9800,   780,    35,     8],
       [  109,  2500,   620,    15,     3],
       [  110, 11000,   800,    38,     9]])

In [250]:
# Q9.2: Calculate the square root of all account balances
np.sqrt(banking_data[:,1])


array([ 70.71067812, 109.5445115 ,  54.77225575,  92.19544457,
        44.72135955, 122.47448714,  67.08203932,  98.99494937,
        50.        , 104.88088482])

In [251]:

# Q9.3: Calculate the square of all credit scores
np.square(banking_data[:,2])


array([518400, 656100, 422500, 592900, 360000, 722500, 476100, 608400,
       384400, 640000])

In [252]:
# Q9.4: Calculate the exponential of all transaction counts
np.exp(banking_data[:,3])


array([7.20048993e+10, 2.35385267e+17, 6.56599691e+07, 1.06864746e+13,
       1.62754791e+05, 5.18470553e+21, 3.58491285e+09, 1.58601345e+15,
       3.26901737e+06, 3.18559318e+16])

In [253]:

# Q9.5: Calculate the natural logarithm of all account balances
np.log(banking_data[:,1])

array([8.51719319, 9.39266193, 8.00636757, 9.04782144, 7.60090246,
       9.61580548, 8.41183268, 9.19013766, 7.82404601, 9.30565055])

In [254]:
# Q10.1: Calculate the cumulative sum of account balances
np.cumsum(banking_data[:,1])

array([ 5000, 17000, 20000, 28500, 30500, 45500, 50000, 59800, 62300,
       73300])

In [255]:
# Q10.2: Calculate the cumulative product of transaction counts
np.cumprod(banking_data[:,3])


array([             25,            1000,           18000,          540000,
               6480000,       324000000,      7128000000,    249480000000,
         3742200000000, 142203600000000])

In [256]:

# Q10.3: Calculate the difference between consecutive account balances
np.diff(banking_data[:,1])

array([  7000,  -9000,   5500,  -6500,  13000, -10500,   5300,  -7300,
         8500])

In [257]:
# Q10.4: Calculate the gradient of account balances
np.gradient(banking_data[:,1])



array([ 7000., -1000., -1750.,  -500.,  3250.,  1250., -2600., -1000.,
         600.,  8500.])

In [258]:
# Q10.5: Calculate the histogram of account balances with 5 bins
np.histogram(banking_data[:,1],bins=5)



(array([4, 1, 1, 3, 1]),
 array([ 2000.,  4600.,  7200.,  9800., 12400., 15000.]))

In [259]:

# Q11.1: Generate 6 random integers between 1 and 1000
np.random.randint(1,1000,6)


array([596, 107, 124, 570, 215, 738], dtype=int32)

In [260]:

# Q11.2: Generate 6 random floats between 0 and 1
np.random.rand(6)


array([0.68482974, 0.4809319 , 0.39211752, 0.34317802, 0.72904971,
       0.43857224])

In [261]:

# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
np.random.normal(700,100,6)


array([685.66275259, 638.08090993, 623.05665285, 757.67460214,
       712.65259202, 569.85110255])

In [262]:

# Q11.4: Shuffle the banking_data rows randomly
np.random.shuffle(banking_data)



In [263]:
# Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
np.random.rand(4)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

In [264]:
# Q12.1: Calculate the dot product of account balance and credit score columns
np.dot(banking_data[:,1],banking_data[:,2])


np.int64(56864000)

In [265]:

# Q12.2: Calculate the cross product of first two rows
np.cross(banking_data[0,:3], banking_data[1,:3])



array([4030000,   10140, -685400])

In [266]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
np.linalg.norm(banking_data[:,1])



np.float64(26884.75404388145)

In [267]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)


np.float64(0.0)

In [268]:
# Q12.5: Calculate the inverse of the 3x3 matrix
# np.linalg.inv(A)


In [269]:

# Q13.1: Convert all customer IDs to strings
banking_data[:,0].astype(str)


array(['108', '103', '110', '107', '104', '102', '101', '106', '109',
       '105'], dtype='<U21')

In [270]:

# Q13.2: Check if any customer ID contains '100'
np.char.find(banking_data[:,0].astype(str),'100')



array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [271]:
# Q13.3: Convert all customer IDs to uppercase
np.char.upper(banking_data[:,0].astype(str))



array(['108', '103', '110', '107', '104', '102', '101', '106', '109',
       '105'], dtype='<U21')

In [272]:
# Q13.4: Count the length of each customer ID string
np.char.str_len(banking_data[:,0].astype(str))



array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [273]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
np.char.replace(banking_data[:,0].astype(str),'100','CUST')



array(['108', '103', '110', '107', '104', '102', '101', '106', '109',
       '105'], dtype='<U3')

In [274]:

# Q14.1: Convert years active to months
banking_data[:,4]*12


array([ 96,  36, 108,  48,  84, 120,  60, 144,  36,  24])

In [275]:

# Q14.2: Calculate the average years active
np.mean(banking_data[:,4])


np.float64(6.3)

In [276]:

# Q14.3: Find customers who have been active for more than 5 years
banking_data[banking_data[:,4]>5]


array([[  108,  9800,   780,    35,     8],
       [  110, 11000,   800,    38,     9],
       [  104,  8500,   770,    30,     7],
       [  102, 12000,   810,    40,    10],
       [  106, 15000,   850,    50,    12]])

In [277]:

# Q14.4: Calculate the total time all customers have been active
np.sum(banking_data[:,4])


np.int64(63)

In [278]:

# Q14.5: Find the customer with the shortest time active
banking_data[np.argmin(banking_data[:,4])]


array([ 105, 2000,  600,   12,    2])

In [279]:


# Q15.1: Apply a function to calculate 5% interest on all account balances
banking_data[:,1]*0.05


array([490., 150., 550., 225., 425., 600., 250., 750., 125., 100.])

In [280]:

# Q15.2: Use np.where to categorize customers by balance ranges
np.where(banking_data[:,1]>10000,'High','Low')


array(['Low', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'High', 'Low',
       'Low'], dtype='<U4')

In [281]:

# Q15.3: Use np.select to categorize customers by credit score ranges
np.select([banking_data[:,2]>750,banking_data[:,2]>650],
          ['Excellent','Good'],'Average')


array(['Excellent', 'Average', 'Excellent', 'Good', 'Excellent',
       'Excellent', 'Good', 'Excellent', 'Average', 'Average'],
      dtype='<U9')

In [282]:

# Q15.4: Use np.piecewise to apply different interest rates based on balance
np.piecewise(banking_data[:,1],
             [banking_data[:,1]<5000,banking_data[:,1]>=5000],
             [0.03,0.05])


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [283]:

# Q15.5: Use np.apply_along_axis to calculate the sum of each row
np.apply_along_axis(np.sum,1,banking_data)



array([10731,  3774, 11957,  5323,  9411, 12962,  5851, 16018,  3247,
        2719])

In [284]:

# Q16.1: Concatenate two arrays horizontally
np.hstack((banking_data,banking_data))


array([[  108,  9800,   780,    35,     8,   108,  9800,   780,    35,
            8],
       [  103,  3000,   650,    18,     3,   103,  3000,   650,    18,
            3],
       [  110, 11000,   800,    38,     9,   110, 11000,   800,    38,
            9],
       [  107,  4500,   690,    22,     4,   107,  4500,   690,    22,
            4],
       [  104,  8500,   770,    30,     7,   104,  8500,   770,    30,
            7],
       [  102, 12000,   810,    40,    10,   102, 12000,   810,    40,
           10],
       [  101,  5000,   720,    25,     5,   101,  5000,   720,    25,
            5],
       [  106, 15000,   850,    50,    12,   106, 15000,   850,    50,
           12],
       [  109,  2500,   620,    15,     3,   109,  2500,   620,    15,
            3],
       [  105,  2000,   600,    12,     2,   105,  2000,   600,    12,
            2]])

In [285]:

# Q16.2: Concatenate two arrays vertically
np.vstack((banking_data,banking_data))


array([[  108,  9800,   780,    35,     8],
       [  103,  3000,   650,    18,     3],
       [  110, 11000,   800,    38,     9],
       [  107,  4500,   690,    22,     4],
       [  104,  8500,   770,    30,     7],
       [  102, 12000,   810,    40,    10],
       [  101,  5000,   720,    25,     5],
       [  106, 15000,   850,    50,    12],
       [  109,  2500,   620,    15,     3],
       [  105,  2000,   600,    12,     2],
       [  108,  9800,   780,    35,     8],
       [  103,  3000,   650,    18,     3],
       [  110, 11000,   800,    38,     9],
       [  107,  4500,   690,    22,     4],
       [  104,  8500,   770,    30,     7],
       [  102, 12000,   810,    40,    10],
       [  101,  5000,   720,    25,     5],
       [  106, 15000,   850,    50,    12],
       [  109,  2500,   620,    15,     3],
       [  105,  2000,   600,    12,     2]])

In [286]:

# Q16.3: Concatenate arrays along a specific axis
np.concatenate((banking_data,banking_data),axis=0)


array([[  108,  9800,   780,    35,     8],
       [  103,  3000,   650,    18,     3],
       [  110, 11000,   800,    38,     9],
       [  107,  4500,   690,    22,     4],
       [  104,  8500,   770,    30,     7],
       [  102, 12000,   810,    40,    10],
       [  101,  5000,   720,    25,     5],
       [  106, 15000,   850,    50,    12],
       [  109,  2500,   620,    15,     3],
       [  105,  2000,   600,    12,     2],
       [  108,  9800,   780,    35,     8],
       [  103,  3000,   650,    18,     3],
       [  110, 11000,   800,    38,     9],
       [  107,  4500,   690,    22,     4],
       [  104,  8500,   770,    30,     7],
       [  102, 12000,   810,    40,    10],
       [  101,  5000,   720,    25,     5],
       [  106, 15000,   850,    50,    12],
       [  109,  2500,   620,    15,     3],
       [  105,  2000,   600,    12,     2]])

In [287]:

# Q16.4: Stack arrays depth-wise
np.dstack((banking_data,banking_data))


array([[[  108,   108],
        [ 9800,  9800],
        [  780,   780],
        [   35,    35],
        [    8,     8]],

       [[  103,   103],
        [ 3000,  3000],
        [  650,   650],
        [   18,    18],
        [    3,     3]],

       [[  110,   110],
        [11000, 11000],
        [  800,   800],
        [   38,    38],
        [    9,     9]],

       [[  107,   107],
        [ 4500,  4500],
        [  690,   690],
        [   22,    22],
        [    4,     4]],

       [[  104,   104],
        [ 8500,  8500],
        [  770,   770],
        [   30,    30],
        [    7,     7]],

       [[  102,   102],
        [12000, 12000],
        [  810,   810],
        [   40,    40],
        [   10,    10]],

       [[  101,   101],
        [ 5000,  5000],
        [  720,   720],
        [   25,    25],
        [    5,     5]],

       [[  106,   106],
        [15000, 15000],
        [  850,   850],
        [   50,    50],
        [   12,    12]],

       [[  109,   109],


In [288]:

# Q16.5: Create a column stack
np.column_stack((banking_data[:,1],banking_data[:,2]))



array([[ 9800,   780],
       [ 3000,   650],
       [11000,   800],
       [ 4500,   690],
       [ 8500,   770],
       [12000,   810],
       [ 5000,   720],
       [15000,   850],
       [ 2500,   620],
       [ 2000,   600]])

In [289]:

# Q17.1: Split array into 3 equal parts
np.split(banking_data,2)


[array([[  108,  9800,   780,    35,     8],
        [  103,  3000,   650,    18,     3],
        [  110, 11000,   800,    38,     9],
        [  107,  4500,   690,    22,     4],
        [  104,  8500,   770,    30,     7]]),
 array([[  102, 12000,   810,    40,    10],
        [  101,  5000,   720,    25,     5],
        [  106, 15000,   850,    50,    12],
        [  109,  2500,   620,    15,     3],
        [  105,  2000,   600,    12,     2]])]

In [290]:

# Q17.2: Split array at specific indices
np.split(banking_data,[3,6])


[array([[  108,  9800,   780,    35,     8],
        [  103,  3000,   650,    18,     3],
        [  110, 11000,   800,    38,     9]]),
 array([[  107,  4500,   690,    22,     4],
        [  104,  8500,   770,    30,     7],
        [  102, 12000,   810,    40,    10]]),
 array([[  101,  5000,   720,    25,     5],
        [  106, 15000,   850,    50,    12],
        [  109,  2500,   620,    15,     3],
        [  105,  2000,   600,    12,     2]])]

In [291]:

# Q17.3: Split array horizontally
np.hsplit(banking_data,[2])


[array([[  108,  9800],
        [  103,  3000],
        [  110, 11000],
        [  107,  4500],
        [  104,  8500],
        [  102, 12000],
        [  101,  5000],
        [  106, 15000],
        [  109,  2500],
        [  105,  2000]]),
 array([[780,  35,   8],
        [650,  18,   3],
        [800,  38,   9],
        [690,  22,   4],
        [770,  30,   7],
        [810,  40,  10],
        [720,  25,   5],
        [850,  50,  12],
        [620,  15,   3],
        [600,  12,   2]])]

In [292]:

# Q17.4: Split array vertically
np.vsplit(banking_data,2)


[array([[  108,  9800,   780,    35,     8],
        [  103,  3000,   650,    18,     3],
        [  110, 11000,   800,    38,     9],
        [  107,  4500,   690,    22,     4],
        [  104,  8500,   770,    30,     7]]),
 array([[  102, 12000,   810,    40,    10],
        [  101,  5000,   720,    25,     5],
        [  106, 15000,   850,    50,    12],
        [  109,  2500,   620,    15,     3],
        [  105,  2000,   600,    12,     2]])]

In [293]:

# Q17.5: Split array into equal chunks
np.array_split(banking_data,4)



[array([[  108,  9800,   780,    35,     8],
        [  103,  3000,   650,    18,     3],
        [  110, 11000,   800,    38,     9]]),
 array([[  107,  4500,   690,    22,     4],
        [  104,  8500,   770,    30,     7],
        [  102, 12000,   810,    40,    10]]),
 array([[  101,  5000,   720,    25,     5],
        [  106, 15000,   850,    50,    12]]),
 array([[ 109, 2500,  620,   15,    3],
        [ 105, 2000,  600,   12,    2]])]

In [294]:

# Q18.1: Repeat each element 3 times
np.repeat(banking_data[:,0],3)


array([108, 108, 108, 103, 103, 103, 110, 110, 110, 107, 107, 107, 104,
       104, 104, 102, 102, 102, 101, 101, 101, 106, 106, 106, 109, 109,
       109, 105, 105, 105])

In [295]:

# Q18.2: Repeat entire array 2 times
np.tile(banking_data,2)


array([[  108,  9800,   780,    35,     8,   108,  9800,   780,    35,
            8],
       [  103,  3000,   650,    18,     3,   103,  3000,   650,    18,
            3],
       [  110, 11000,   800,    38,     9,   110, 11000,   800,    38,
            9],
       [  107,  4500,   690,    22,     4,   107,  4500,   690,    22,
            4],
       [  104,  8500,   770,    30,     7,   104,  8500,   770,    30,
            7],
       [  102, 12000,   810,    40,    10,   102, 12000,   810,    40,
           10],
       [  101,  5000,   720,    25,     5,   101,  5000,   720,    25,
            5],
       [  106, 15000,   850,    50,    12,   106, 15000,   850,    50,
           12],
       [  109,  2500,   620,    15,     3,   109,  2500,   620,    15,
            3],
       [  105,  2000,   600,    12,     2,   105,  2000,   600,    12,
            2]])

In [296]:

# Q18.3: Repeat a 2D array
np.tile(banking_data,(2,2))


array([[  108,  9800,   780,    35,     8,   108,  9800,   780,    35,
            8],
       [  103,  3000,   650,    18,     3,   103,  3000,   650,    18,
            3],
       [  110, 11000,   800,    38,     9,   110, 11000,   800,    38,
            9],
       [  107,  4500,   690,    22,     4,   107,  4500,   690,    22,
            4],
       [  104,  8500,   770,    30,     7,   104,  8500,   770,    30,
            7],
       [  102, 12000,   810,    40,    10,   102, 12000,   810,    40,
           10],
       [  101,  5000,   720,    25,     5,   101,  5000,   720,    25,
            5],
       [  106, 15000,   850,    50,    12,   106, 15000,   850,    50,
           12],
       [  109,  2500,   620,    15,     3,   109,  2500,   620,    15,
            3],
       [  105,  2000,   600,    12,     2,   105,  2000,   600,    12,
            2],
       [  108,  9800,   780,    35,     8,   108,  9800,   780,    35,
            8],
       [  103,  3000,   650,    18,     3, 

In [297]:

# Q18.4: Create a pattern
np.tile([1,2,3],4)


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [298]:

# Q18.5: Repeat elements with different counts
np.repeat([1,2,3],[1,2,3])


array([1, 2, 2, 3, 3, 3])

In [299]:


# Q19.1: Compare two arrays for equality
np.array_equal(banking_data,banking_data)


True

In [300]:

# Q19.2: Check if arrays are close
np.allclose(banking_data,banking_data)



True

In [301]:
# Q19.3: Logical AND operation
np.logical_and(banking_data[:,1]>5000, banking_data[:,2]>700)


array([ True, False,  True, False,  True,  True, False,  True, False,
       False])

In [302]:

# Q19.4: Logical OR operation
np.logical_or(banking_data[:,1]>5000, banking_data[:,2]>700)


array([ True, False,  True, False,  True,  True,  True,  True, False,
       False])

In [303]:

# Q19.5: Logical NOT operation
np.logical_not(banking_data[:,1]>5000)



array([False,  True, False,  True, False, False,  True, False,  True,
        True])

In [304]:

# Q20.1: Find unique elements
np.unique(banking_data[:,0])


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [305]:

# Q20.2: Intersection of two arrays
np.intersect1d([1,2,3],[2,3,4])


array([2, 3])

In [306]:

# Q20.3: Union of two arrays
np.union1d([1,2,3],[2,3,4])


array([1, 2, 3, 4])

In [307]:

# Q20.4: Elements in first array but not second
np.setdiff1d([1,2,3],[2,3])


array([1])

In [308]:

# Q20.5: Symmetric difference
np.setxor1d([1,2,3],[2,3,4])

array([1, 4])