In [3]:
# ramdom functions
import numpy as np
np.random.randint(0,100)

81

In [2]:
import numpy as np
np.random.randint(0,100,(5,2))

array([[56, 50],
       [15, 91],
       [ 0, 72],
       [ 1, 24],
       [95, 95]], dtype=int32)

In [3]:
np.random.randint(0,100,(5,2,3))

array([[[39,  0, 86],
        [ 6, 11, 59]],

       [[79, 25, 57],
        [60, 65, 71]],

       [[43, 46, 44],
        [13,  2, 79]],

       [[50, 24, 37],
        [61, 77, 16]],

       [[84,  3, 97],
        [ 0, 68, 40]]], dtype=int32)

In [4]:
np.random.randint(0,100,(3,3))

array([[25, 84, 33],
       [17, 76, 20],
       [96, 50, 81]], dtype=int32)

In [5]:
data = np.random.rand(3,3)
data

array([[0.46835624, 0.63674879, 0.05187439],
       [0.80089379, 0.17944706, 0.27385239],
       [0.06765098, 0.83482848, 0.75556564]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [8]:
np.arange(10,0,-3)

array([10,  7,  4,  1])

In [9]:
range(0,10)

range(0, 10)

In [10]:
# 1 to 100
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
data = np.random.randint(0,100,(3,3))

In [14]:
data 

array([[ 4, 71,  1],
       [80, 95, 38],
       [31, 80, 77]], dtype=int32)

In [ ]:
data.shape

(3, 3)

In [ ]:
data.size

9

In [ ]:
data.T

array([[54, 98, 13],
       [30, 44, 16],
       [85,  2, 76]], dtype=int32)

In [4]:
np.random.seed(121)
data = np.random.randint(0,100,(5,5))
data

array([[66, 85,  8, 95, 65],
       [52, 83, 96, 46, 34],
       [52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39],
       [21, 41, 55, 83, 94]], dtype=int32)

In [5]:
data[0,0]

np.int32(66)

In [6]:
data[2,2]

np.int32(54)

In [ ]:
data[0:2,0:2]

array([[66, 85],
       [52, 83]], dtype=int32)

In [ ]:
data

array([[66, 85,  8, 95, 65],
       [52, 83, 96, 46, 34],
       [52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39],
       [21, 41, 55, 83, 94]], dtype=int32)

In [ ]:
data[3:5,3:5]

array([[88, 39],
       [83, 94]], dtype=int32)

In [ ]:
data[1:3,1:3]

array([[83, 96],
       [60, 54]], dtype=int32)

In [ ]:
data[0:4,0:2]

array([[66, 85],
       [52, 83],
       [52, 60],
       [52, 57]], dtype=int32)

In [ ]:
data[0:4,4]

array([65, 34, 94, 39], dtype=int32)

In [ ]:
data[0,4]

np.int32(65)

In [ ]:
data

array([[66, 85,  8, 95, 65],
       [52, 83, 96, 46, 34],
       [52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39],
       [21, 41, 55, 83, 94]], dtype=int32)

In [20]:
data[-3:,-1:]

array([[94],
       [39],
       [94]], dtype=int32)

In [16]:
data[1:3,-2:]

array([[46, 34],
       [ 3, 94]], dtype=int32)

In [15]:
data[2:4]

array([[52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39]], dtype=int32)

In [ ]:
data[-1]

array([21, 41, 55, 83, 94], dtype=int32)

In [10]:
data[-1,3]

np.int32(83)

In [ ]:
data[-3,1]

np.int32(60)

In [ ]:
data=np.random.randint(0,10,(3,3))

In [22]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [23]:
data.sum()

np.int64(44)

In [24]:
data.sum(axis=1)

array([15,  9, 20])