In [1320]:
import pandas as pd

In [1321]:
import numpy as np


In [1322]:
print("=" * 60)
print("NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS")
print("=" * 60)

NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS


In [1323]:
# Create retail data: 10 rows × 5 columns
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

In [1324]:
retail_data

array([[1001.  ,   29.99,   45.  ,    4.2 ,   15.  ],
       [1002.  ,   49.99,   32.  ,    4.5 ,    8.  ],
       [1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ],
       [1007.  ,   39.99,   56.  ,    3.9 ,   20.  ],
       [1008.  ,   79.99,   18.  ,    4.6 ,    7.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ],
       [1010.  ,   59.99,   34.  ,    4.4 ,   10.  ]])

In [1325]:
print("\nORIGINAL RETAIL DATA:")
print(retail_data)
print(f"\nData shape: {retail_data.shape}")
print(f"Data type: {retail_data.dtype}")



ORIGINAL RETAIL DATA:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Data shape: (10, 5)
Data type: float64


In [1326]:
print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")
print("Answer:")
identity_matrix = np.eye(3)
print(identity_matrix)




Q1.1: Create a 3x3 identity matrix using np.eye()
Answer:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1327]:
print("\nQ1.2: Create an array of 10 zeros using np.zeros()")
print("Answer:")
zeros_array = np.zeros(10)
print(zeros_array)


Q1.2: Create an array of 10 zeros using np.zeros()
Answer:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [1328]:
print("\nQ1.3: Create an array of 5 ones using np.ones()")
print("Answer:")
ones_array = np.ones(5)
print(ones_array)



Q1.3: Create an array of 5 ones using np.ones()
Answer:
[1. 1. 1. 1. 1.]


In [1329]:
print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")
print("Answer:")
range_array = np.arange(10)
print(range_array)


Q1.4: Create an array with values from 0 to 9 using np.arange()
Answer:
[0 1 2 3 4 5 6 7 8 9]


In [1330]:
print("\nQ1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()")
print("Answer:")
linspace_array = np.linspace(0, 10, 6)
print(linspace_array)



Q1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()
Answer:
[ 0.  2.  4.  6.  8. 10.]


In [1331]:
# QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION
print("\nQ2.1: What is the shape of the retail_data array?")
print("Answer:")
print(f"Shape: {retail_data.shape}")


Q2.1: What is the shape of the retail_data array?
Answer:
Shape: (10, 5)


In [1332]:
print("\nQ2.2: What is the data type of the retail_data array?")
print("Answer:")
print(f"Data type: {retail_data.dtype}")


Q2.2: What is the data type of the retail_data array?
Answer:
Data type: float64


In [1333]:
print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")
print("Answer:")
print(f"Size: {retail_data.size}")


Q2.3: What is the size (total number of elements) of the retail_data array?
Answer:
Size: 50


In [1334]:
print("\nQ2.4: What is the number of dimensions of the retail_data array?")
print("Answer:")
print(f"Dimensions: {retail_data.ndim}")


Q2.4: What is the number of dimensions of the retail_data array?
Answer:
Dimensions: 2


In [1335]:
print("\nQ2.5: What is the memory size of the retail_data array in bytes?")
print("Answer:")
print(f"Memory size: {retail_data.nbytes} bytes")


Q2.5: What is the memory size of the retail_data array in bytes?
Answer:
Memory size: 400 bytes


### QUESTION 3: INDEXING AND SLICING

In [1336]:
print("\nQ3.1: Extract the first row of retail_data")
print("Answer:")
first_row = retail_data[0]
print(first_row)


Q3.1: Extract the first row of retail_data
Answer:
[1001.     29.99   45.      4.2    15.  ]


In [1337]:
print("\nQ3.2: Extract the last row of retail_data")
print("Answer:")
last_row = retail_data[-1]
print(last_row)


Q3.2: Extract the last row of retail_data
Answer:
[1010.     59.99   34.      4.4    10.  ]


In [1338]:
print("\nQ3.3: Extract the Price column (column index 1)")
print("Answer:")
price_column = retail_data[:, 1]
print(price_column)


Q3.3: Extract the Price column (column index 1)
Answer:
[29.99 49.99 19.99 89.99 15.99 69.99 39.99 79.99 25.99 59.99]


In [1339]:
print("\nQ3.4: Extract the first 3 rows and first 2 columns")
print("Answer:")
subset = retail_data[:3, :2]
print(subset)


Q3.4: Extract the first 3 rows and first 2 columns
Answer:
[[1001.     29.99]
 [1002.     49.99]
 [1003.     19.99]]


In [1340]:
print("\nQ3.5: Extract rows 2 to 5 (inclusive)")
print("Answer:")
rows_2_to_5 = retail_data[2:6]
print(rows_2_to_5)


Q3.5: Extract rows 2 to 5 (inclusive)
Answer:
[[1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]]


### QUESTION 4: MATHEMATICAL OPERATIONS

In [1341]:
print("\nQ4.1: Calculate the sum of all prices")
print("Answer:")
total_price = np.sum(retail_data[:, 1])
print(f"Total price: ${total_price:.2f}")


Q4.1: Calculate the sum of all prices
Answer:
Total price: $481.90


In [1342]:
print("\nQ4.2: Calculate the mean price")
print("Answer:")
mean_price = np.mean(retail_data[:, 1])
print(f"Mean price: ${mean_price:.2f}")



Q4.2: Calculate the mean price
Answer:
Mean price: $48.19


In [1343]:
print("\nQ4.4: Calculate the variance of prices")
print("Answer:")
var_price = np.var(retail_data[:, 1])
print(f"Variance of prices: ${var_price:.2f}")




Q4.4: Calculate the variance of prices
Answer:
Variance of prices: $609.96


In [1344]:
print("\nQ4.5: Calculate the median price")
print("Answer:")
median_price = np.median(retail_data[:, 1])
print(f"Median price: ${median_price:.2f}")


Q4.5: Calculate the median price
Answer:
Median price: $44.99


### QUESTION 5: STATISTICAL FUNCTIONS

In [1345]:
print("\nQ5.1: Find the minimum and maximum prices")
print("Answer:")
min_price = np.min(retail_data[:, 1])
max_price = np.max(retail_data[:, 1])
print(f"Minimum price: ${min_price:.2f}")
print(f"Maximum price: ${max_price:.2f}")




Q5.1: Find the minimum and maximum prices
Answer:
Minimum price: $15.99
Maximum price: $89.99


In [1346]:
print("\nQ5.2: Find the minimum and maximum quantities sold")
print("Answer:")
min_qty = np.min(retail_data[:, 2])
max_qty = np.min(retail_data[:, 2])
print(f"Minimum quantity: {min_qty}")
print(f"Maximum quantity: {max_qty}")




Q5.2: Find the minimum and maximum quantities sold
Answer:
Minimum quantity: 12.0
Maximum quantity: 12.0


In [1347]:
print("\nQ5.3: Calculate the percentile values for prices (25th, 50th, 75th)")
print("Answer:")
percentiles = np.percentile(retail_data[:, 1], [25, 50, 75])
print(f"25th percentile: ${percentiles[0]:.2f}")
print(f"50th percentile: ${percentiles[1]:.2f}")
print(f"75th percentile: ${percentiles[2]:.2f}")




Q5.3: Calculate the percentile values for prices (25th, 50th, 75th)
Answer:
25th percentile: $26.99
50th percentile: $44.99
75th percentile: $67.49


In [1348]:
print("\nQ5.4: Calculate the correlation between prices and quantities sold")
print("Answer:")
correlation = np.corrcoef(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Correlation: {correlation:.4f}")




Q5.4: Calculate the correlation between prices and quantities sold
Answer:
Correlation: -0.9291


In [1349]:
print("\nQ5.5: Calculate the covariance between prices and quantities sold")
print("Answer:")
covariance = np.cov(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Covariance: {covariance:.4f}")


Q5.5: Calculate the covariance between prices and quantities sold
Answer:
Covariance: -653.4444


### QUESTION 6: ARRAY RESHAPING AND MANIPULATION

In [1350]:
print("\nQ6.1: Reshape the retail_data to 5 rows × 10 columns")
print("Answer:")
reshaped_5x10 = retail_data.reshape(5, 10)
print(reshaped_5x10)




Q6.1: Reshape the retail_data to 5 rows × 10 columns
Answer:
[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]


In [1351]:
print("\nQ6.2: Flatten the retail_data to a 1D array")
print("Answer:")
flattened = retail_data.flatten()
print(flattened)




Q6.2: Flatten the retail_data to a 1D array
Answer:
[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
    8.   1003.     19.99   78.      3.8    22.   1004.     89.99   12.
    4.7     5.   1005.     15.99   95.      4.     18.   1006.     69.99
   28.      4.3    12.   1007.     39.99   56.      3.9    20.   1008.
   79.99   18.      4.6     7.   1009.     25.99   67.      4.1    16.
 1010.     59.99   34.      4.4    10.  ]


In [1352]:
print("\nQ6.3: Transpose the retail_data")
print("Answer:")
transposed = retail_data.T
print(transposed)




Q6.3: Transpose the retail_data
Answer:
[[1001.   1002.   1003.   1004.   1005.   1006.   1007.   1008.   1009.
  1010.  ]
 [  29.99   49.99   19.99   89.99   15.99   69.99   39.99   79.99   25.99
    59.99]
 [  45.     32.     78.     12.     95.     28.     56.     18.     67.
    34.  ]
 [   4.2     4.5     3.8     4.7     4.      4.3     3.9     4.6     4.1
     4.4 ]
 [  15.      8.     22.      5.     18.     12.     20.      7.     16.
    10.  ]]


In [1353]:
print("\nQ6.4: Split the retail_data into 2 equal parts vertically")
print("Answer:")
split_vertical = np.vsplit(retail_data, 2)
print("First part:")
print(split_vertical[0])
print("\nSecond part:")
print(split_vertical[1])




Q6.4: Split the retail_data into 2 equal parts vertically
Answer:
First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [1354]:
print("\nQ6.5: Split the retail_data into 2 equal parts horizontally")
print("Answer:")
split_horizontal = np.split(retail_data, 2)
print("First part:")
print(split_horizontal[0])
print("\nSecond part:")
print(split_horizontal[1])


Q6.5: Split the retail_data into 2 equal parts horizontally
Answer:
First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


#### QUESTION 7: LOGICAL OPERATIONS AND FILTERING

In [1355]:
print("\nQ7.1: Find products with price greater than $50")
print("Answer:")
expensive_products = retail_data[retail_data[:, 1] > 50]
print(expensive_products)



Q7.1: Find products with price greater than $50
Answer:
[[1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [1356]:

print("\nQ7.2: Find products with customer rating greater than 4.0")
print("Answer:")
high_rated = retail_data[retail_data[:, 3] > 4.0]
print(high_rated)




Q7.2: Find products with customer rating greater than 4.0
Answer:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [1357]:
print("\nQ7.3: Find products with quantity sold greater than 50 AND price less than $40")
print("Answer:")
popular_affordable = retail_data[(retail_data[:, 2] > 50) & (retail_data[:, 1] < 40)]
print(popular_affordable)



Q7.3: Find products with quantity sold greater than 50 AND price less than $40
Answer:
[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]


In [1358]:

print("\nQ7.4: Count how many products have price between $20 and $60")
print("Answer:")
price_range_count = np.sum((retail_data[:, 1] >= 20) & (retail_data[:, 1] <= 60))
print(f"Products in $20-$60 range: {price_range_count}")



Q7.4: Count how many products have price between $20 and $60
Answer:
Products in $20-$60 range: 5


In [1359]:

print("\nQ7.5: Find the index of the product with the highest rating")
print("Answer:")
highest_rating_idx = np.argmax(retail_data[:, 3])
print(f"Index: {highest_rating_idx}, Product ID: {retail_data[highest_rating_idx, 0]}")


Q7.5: Find the index of the product with the highest rating
Answer:
Index: 3, Product ID: 1004.0


### QUESTION 8: SORTING AND SEARCHING

In [1360]:
print("\nQ8.1: Sort the retail_data by price (ascending)")
print("Answer:")
sorted_by_price = retail_data[retail_data[:, 1].argsort()]
print(sorted_by_price)



Q8.1: Sort the retail_data by price (ascending)
Answer:
[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [1361]:

print("\nQ8.2: Sort the retail_data by quantity sold (descending)")
print("Answer:")
sorted_by_qty_desc = retail_data[(-retail_data[:, 2]).argsort()]
print(sorted_by_qty_desc)



Q8.2: Sort the retail_data by quantity sold (descending)
Answer:
[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [1362]:

print("\nQ8.3: Find the indices that would sort the array by customer rating")
print("Answer:")
rating_sort_indices = np.argsort(retail_data[:, 3])
print(rating_sort_indices)



Q8.3: Find the indices that would sort the array by customer rating
Answer:
[2 6 4 8 0 5 9 1 7 3]


In [1363]:

print("\nQ8.4: Find the product with the second highest price")
print("Answer:")
second_highest_price_idx = np.argsort(retail_data[:, 1])[-2]
second_highest_product = retail_data[second_highest_price_idx]
print(f"Product ID: {second_highest_product[0]}, Price: ${second_highest_product[1]:.2f}")



Q8.4: Find the product with the second highest price
Answer:
Product ID: 1008.0, Price: $79.99


In [1364]:

print("\nQ8.5: Find the product with the lowest quantity sold")
print("Answer:")
lowest_qty_idx = np.argmin(retail_data[:, 2])
lowest_qty_product = retail_data[lowest_qty_idx]
print(f"Product ID: {lowest_qty_product[0]}, Quantity: {lowest_qty_product[2]}")


Q8.5: Find the product with the lowest quantity sold
Answer:
Product ID: 1004.0, Quantity: 12.0


### QUESTION 9: MATHEMATICAL FUNCTIONS


In [1365]:

print("\nQ9.1: Calculate the absolute values of all elements")
print("Answer:")
absolute_values = np.abs(retail_data)
print(absolute_values)




Q9.1: Calculate the absolute values of all elements
Answer:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [1366]:
print("\nQ9.2: Calculate the square root of all prices")
print("Answer:")
sqrt_prices = np.sqrt(retail_data[:, 1])
print(sqrt_prices)




Q9.2: Calculate the square root of all prices
Answer:
[5.47631263 7.07036067 4.47101778 9.48630592 3.9987498  8.36600263
 6.3237647  8.94371288 5.09803884 7.74532117]


In [1367]:
print("\nQ9.3: Calculate the square of all quantities sold")
print("Answer:")
squared_qty = np.square(retail_data[:, 2])
print(squared_qty)



Q9.3: Calculate the square of all quantities sold
Answer:
[2025. 1024. 6084.  144. 9025.  784. 3136.  324. 4489. 1156.]


In [1368]:

print("\nQ9.4: Calculate the exponential of all customer ratings")
print("Answer:")
exp_ratings = np.exp(retail_data[:, 3])
print(exp_ratings)



Q9.4: Calculate the exponential of all customer ratings
Answer:
[ 66.68633104  90.0171313   44.70118449 109.94717245  54.59815003
  73.6997937   49.40244911  99.48431564  60.3402876   81.45086866]


In [1369]:

print("\nQ9.5: Calculate the natural logarithm of all prices")
print("Answer:")
log_prices = np.log(retail_data[:, 1])
print(log_prices)


Q9.5: Calculate the natural logarithm of all prices
Answer:
[3.40086399 3.91182299 2.99523215 4.49969855 2.77196353 4.24835237
 3.68862942 4.38190163 3.25771185 4.09417788]


#### QUESTION 10: ADVANCED OPERATIONS

In [1370]:

print("\nQ10.1: Calculate the cumulative sum of prices")
print("Answer:")
cumsum_prices = np.cumsum(retail_data[:, 1])
print(cumsum_prices)



Q10.1: Calculate the cumulative sum of prices
Answer:
[ 29.99  79.98  99.97 189.96 205.95 275.94 315.93 395.92 421.91 481.9 ]


In [1371]:

print("\nQ10.2: Calculate the cumulative product of quantities sold")
print("Answer:")
cumprod_qty = np.cumprod(retail_data[:, 2])
print(cumprod_qty)



Q10.2: Calculate the cumulative product of quantities sold
Answer:
[4.50000000e+01 1.44000000e+03 1.12320000e+05 1.34784000e+06
 1.28044800e+08 3.58525440e+09 2.00774246e+11 3.61393644e+12
 2.42133741e+14 8.23254720e+15]


In [1372]:

print("\nQ10.3: Calculate the difference between consecutive prices")
print("Answer:")
diff_prices = np.diff(retail_data[:, 1])
print(diff_prices)



Q10.3: Calculate the difference between consecutive prices
Answer:
[ 20. -30.  70. -74.  54. -30.  40. -54.  34.]


In [1373]:

print("\nQ10.4: Calculate the gradient of prices")
print("Answer:")
gradient_prices = np.gradient(retail_data[:, 1])
print(gradient_prices)



Q10.4: Calculate the gradient of prices
Answer:
[ 20.  -5.  20.  -2. -10.  12.   5.  -7. -10.  34.]


In [1374]:

print("\nQ10.5: Calculate the histogram of prices with 5 bins")
print("Answer:")
hist_prices, bin_edges = np.histogram(retail_data[:, 1], bins=5)
print(f"Histogram counts: {hist_prices}")
print(f"Bin edges: {bin_edges}")


Q10.5: Calculate the histogram of prices with 5 bins
Answer:
Histogram counts: [4 1 2 1 2]
Bin edges: [15.99 30.79 45.59 60.39 75.19 89.99]


### QUESTION 11: RANDOM NUMBERS AND SIMULATION

In [1375]:
print("\nQ11.1: Generate 5 random integers between 1 and 100")
print("Answer:")
random_ints = np.random.randint(1, 101, 5)
print(random_ints)



Q11.1: Generate 5 random integers between 1 and 100
Answer:
[61 21 83 87 75]


In [1376]:

print("\nQ11.2: Generate 5 random floats between 0 and 1")
print("Answer:")
random_floats = np.random.random(5)
print(random_floats)



Q11.2: Generate 5 random floats between 0 and 1
Answer:
[0.45924889 0.33370861 0.14286682 0.65088847 0.05641158]


In [1377]:

print("\nQ11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)")
print("Answer:")
normal_random = np.random.normal(0, 1, 5)
print(normal_random)



Q11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)
Answer:
[ 0.23309524  0.11799461  1.46237812  1.53871497 -2.43910582]


In [1378]:

print("\nQ11.4: Shuffle the retail_data rows randomly")
print("Answer:")
shuffled_data = retail_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)



Q11.4: Shuffle the retail_data rows randomly
Answer:
[[1002.     49.99   32.      4.5     8.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1003.     19.99   78.      3.8    22.  ]]


In [1379]:

print("\nQ11.5: Set random seed to 42 and generate 3 random numbers")
print("Answer:")
np.random.seed(42)
seeded_random = np.random.random(3)
print(seeded_random)


Q11.5: Set random seed to 42 and generate 3 random numbers
Answer:
[0.37454012 0.95071431 0.73199394]


### QUESTION 11: RANDOM NUMBERS AND SIMULATION

In [1380]:

print("\nQ11.1: Generate 5 random integers between 1 and 100")
print("Answer:")
random_ints = np.random.randint(1, 101, 5)
print(random_ints)



Q11.1: Generate 5 random integers between 1 and 100
Answer:
[61 21 83 87 75]


In [1381]:

print("\nQ11.2: Generate 5 random floats between 0 and 1")
print("Answer:")
random_floats = np.random.random(5)
print(random_floats)



Q11.2: Generate 5 random floats between 0 and 1
Answer:
[0.45924889 0.33370861 0.14286682 0.65088847 0.05641158]


In [1382]:

print("\nQ11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)")
print("Answer:")
normal_random = np.random.normal(0, 1, 5)
print(normal_random)



Q11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)
Answer:
[ 0.23309524  0.11799461  1.46237812  1.53871497 -2.43910582]


In [1383]:

print("\nQ11.4: Shuffle the retail_data rows randomly")
print("Answer:")
shuffled_data = retail_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)



Q11.4: Shuffle the retail_data rows randomly
Answer:
[[1002.     49.99   32.      4.5     8.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1003.     19.99   78.      3.8    22.  ]]


In [1384]:

print("\nQ11.5: Set random seed to 42 and generate 3 random numbers")
print("Answer:")
np.random.seed(42)
seeded_random = np.random.random(3)
print(seeded_random)



Q11.5: Set random seed to 42 and generate 3 random numbers
Answer:
[0.37454012 0.95071431 0.73199394]


#### QUESTION 12: LINEAR ALGEBRA OPERATIONS

In [1385]:
print("\nQ12.1: Calculate the dot product of price and quantity columns")
print("Answer:")
dot_product = np.dot(retail_data[:, 1], retail_data[:, 2])
print(f"Dot product: {dot_product:.2f}")



Q12.1: Calculate the dot product of price and quantity columns
Answer:
Dot product: 16527.35


In [1386]:

print("\nQ12.2: Calculate the cross product of first two rows")
print("Answer:")
cross_product = np.cross(retail_data[0, :3], retail_data[1, :3])
print(cross_product)



Q12.2: Calculate the cross product of first two rows
Answer:
[-1289.87 13058.   19990.01]


In [1387]:

print("\nQ12.3: Calculate the norm (magnitude) of the price column")
print("Answer:")
price_norm = np.linalg.norm(retail_data[:, 1])
print(f"Price norm: {price_norm:.2f}")



Q12.3: Calculate the norm (magnitude) of the price column
Answer:
Price norm: 171.24


In [1388]:

print("\nQ12.4: Create a 2x2 matrix and calculate its determinant")
print("Answer:")
matrix_2x2 = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(matrix_2x2)
print(f"Matrix:\n{matrix_2x2}")
print(f"Determinant: {determinant}")



Q12.4: Create a 2x2 matrix and calculate its determinant
Answer:
Matrix:
[[2 3]
 [1 4]]
Determinant: 5.000000000000001


In [1389]:

print("\nQ12.5: Calculate the inverse of the 2x2 matrix")
print("Answer:")
inverse_matrix = np.linalg.inv(matrix_2x2)
print(f"Inverse matrix:\n{inverse_matrix}")



Q12.5: Calculate the inverse of the 2x2 matrix
Answer:
Inverse matrix:
[[ 0.8 -0.6]
 [-0.2  0.4]]


### QUESTION 13: STRING OPERATIONS

In [1390]:

print("\nQ13.1: Convert all product IDs to strings")
print("Answer:")
product_ids_str = retail_data[:, 0].astype(str)
print(product_ids_str)



Q13.1: Convert all product IDs to strings
Answer:
['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [1391]:

print("\nQ13.2: Check if any product ID contains '100'")
print("Answer:")
contains_100 = np.char.find(product_ids_str, '100') >= 0
print(contains_100)



Q13.2: Check if any product ID contains '100'
Answer:
[ True  True  True  True  True  True  True  True  True False]


In [1392]:

print("\nQ13.3: Convert all product IDs to uppercase (if they were strings)")
print("Answer:")
# Since they're numbers, we'll convert to string first
product_ids_upper = np.char.upper(product_ids_str)
print(product_ids_upper)



Q13.3: Convert all product IDs to uppercase (if they were strings)
Answer:
['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [1393]:

print("\nQ13.4: Count the length of each product ID string")
print("Answer:")
id_lengths = np.char.str_len(product_ids_str)
print(id_lengths)



Q13.4: Count the length of each product ID string
Answer:
[6 6 6 6 6 6 6 6 6 6]


In [1394]:

print("\nQ13.5: Replace '100' with 'PROD' in product IDs")
print("Answer:")
replaced_ids = np.char.replace(product_ids_str, '100', 'PROD')
print(replaced_ids)


Q13.5: Replace '100' with 'PROD' in product IDs
Answer:
['PROD1.0' 'PROD2.0' 'PROD3.0' 'PROD4.0' 'PROD5.0' 'PROD6.0' 'PROD7.0'
 'PROD8.0' 'PROD9.0' '1010.0']


#### QUESTION 14: DATE AND TIME OPERATIONS

In [1395]:
print("\nQ14.1: Convert days in stock to hours")
print("Answer:")
days_to_hours = retail_data[:, 4] * 24
print(days_to_hours)



Q14.1: Convert days in stock to hours
Answer:
[360. 192. 528. 120. 432. 288. 480. 168. 384. 240.]


In [1396]:

print("\nQ14.2: Calculate the average days in stock")
print("Answer:")
avg_days = np.mean(retail_data[:, 4])
print(f"Average days in stock: {avg_days:.1f}")



Q14.2: Calculate the average days in stock
Answer:
Average days in stock: 13.3


In [1397]:

print("\nQ14.3: Find products that have been in stock for more than 15 days")
print("Answer:")
long_stock = retail_data[retail_data[:, 4] > 15]
print(long_stock)



Q14.3: Find products that have been in stock for more than 15 days
Answer:
[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]


In [1398]:

print("\nQ14.4: Calculate the total time all products have been in stock (in days)")
print("Answer:")
total_stock_time = np.sum(retail_data[:, 4])
print(f"Total stock time: {total_stock_time} days")



Q14.4: Calculate the total time all products have been in stock (in days)
Answer:
Total stock time: 133.0 days


In [1399]:

print("\nQ14.5: Find the product with the shortest time in stock")
print("Answer:")
shortest_stock_idx = np.argmin(retail_data[:, 4])
shortest_stock_product = retail_data[shortest_stock_idx]
print(f"Product ID: {shortest_stock_product[0]}, Days: {shortest_stock_product[4]}")


Q14.5: Find the product with the shortest time in stock
Answer:
Product ID: 1004.0, Days: 5.0


#### QUESTION 15: ADVANCED ARRAY OPERATIONS

In [1400]:

print("\nQ15.1: Apply a function to square all prices")
print("Answer:")
def square_price(x):
    return x ** 2

squared_prices = np.vectorize(square_price)(retail_data[:, 1])
print(squared_prices)

print("\nQ15.2: Use np.where to replace prices > $50 with 'Expensive' and others with 'Affordable'")
print("Answer:")
price_labels = np.where(retail_data[:, 1] > 50, 'Expensive', 'Affordable')
print(price_labels)

print("\nQ15.3: Use np.select to categorize products by price ranges")
print("Answer:")
conditions = [
    retail_data[:, 1] < 20,
    (retail_data[:, 1] >= 20) & (retail_data[:, 1] < 50),
    retail_data[:, 1] >= 50
]
choices = ['Budget', 'Mid-range', 'Premium']
price_categories = np.select(conditions, choices, default='Unknown')
print(price_categories)

print("\nQ15.4: Use np.piecewise to apply different functions based on price ranges")
print("Answer:")
def low_price(x): return x * 0.9  # 10% discount
def mid_price(x): return x * 1.0  # No change
def high_price(x): return x * 1.1  # 10% markup

discounted_prices = np.piecewise(
    retail_data[:, 1],
    [retail_data[:, 1] < 20, (retail_data[:, 1] >= 20) & (retail_data[:, 1] < 50), retail_data[:, 1] >= 50],
    [low_price, mid_price, high_price]
)
print(discounted_prices)

print("\nQ15.5: Use np.apply_along_axis to calculate the sum of each row")
print("Answer:")
row_sums = np.apply_along_axis(np.sum, 1, retail_data)
print(row_sums)



Q15.1: Apply a function to square all prices
Answer:
[ 899.4001 2499.0001  399.6001 8098.2001  255.6801 4898.6001 1599.2001
 6398.4001  675.4801 3598.8001]

Q15.2: Use np.where to replace prices > $50 with 'Expensive' and others with 'Affordable'
Answer:
['Affordable' 'Affordable' 'Affordable' 'Expensive' 'Affordable'
 'Expensive' 'Affordable' 'Expensive' 'Affordable' 'Expensive']

Q15.3: Use np.select to categorize products by price ranges
Answer:
['Mid-range' 'Mid-range' 'Budget' 'Premium' 'Budget' 'Premium' 'Mid-range'
 'Premium' 'Mid-range' 'Premium']

Q15.4: Use np.piecewise to apply different functions based on price ranges
Answer:
[29.99  49.99  17.991 98.989 14.391 76.989 39.99  87.989 25.99  65.989]

Q15.5: Use np.apply_along_axis to calculate the sum of each row
Answer:
[1095.19 1096.49 1126.79 1115.69 1137.99 1120.29 1126.89 1117.59 1122.09
 1118.39]


#### QUESTION 16: ARRAY CONCATENATION AND STACKING

In [1401]:

print("\nQ16.1: Concatenate two arrays horizontally using np.hstack()")
print("Answer:")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstacked = np.hstack([arr1, arr2])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Horizontally stacked: {hstacked}")

print("\nQ16.2: Concatenate two arrays vertically using np.vstack()")
print("Answer:")
vstacked = np.vstack([arr1, arr2])
print(f"Vertically stacked:\n{vstacked}")

print("\nQ16.3: Concatenate arrays along a specific axis using np.concatenate()")
print("Answer:")
concatenated = np.concatenate([arr1, arr2], axis=0)
print(f"Concatenated along axis 0: {concatenated}")

print("\nQ16.4: Stack arrays depth-wise using np.dstack()")
print("Answer:")
dstacked = np.dstack([arr1, arr2])
print(f"Depth-wise stacked:\n{dstacked}")

print("\nQ16.5: Create a column stack using np.column_stack()")
print("Answer:")
col_stacked = np.column_stack([arr1, arr2])
print(f"Column stacked:\n{col_stacked}")


Q16.1: Concatenate two arrays horizontally using np.hstack()
Answer:
Array 1: [1 2 3]
Array 2: [4 5 6]
Horizontally stacked: [1 2 3 4 5 6]

Q16.2: Concatenate two arrays vertically using np.vstack()
Answer:
Vertically stacked:
[[1 2 3]
 [4 5 6]]

Q16.3: Concatenate arrays along a specific axis using np.concatenate()
Answer:
Concatenated along axis 0: [1 2 3 4 5 6]

Q16.4: Stack arrays depth-wise using np.dstack()
Answer:
Depth-wise stacked:
[[[1 4]
  [2 5]
  [3 6]]]

Q16.5: Create a column stack using np.column_stack()
Answer:
Column stacked:
[[1 4]
 [2 5]
 [3 6]]


#### QUESTION 17: ARRAY SPLITTING OPERATIONS

In [1402]:

print("\nQ17.1: Split an array into 3 equal parts using np.split()")
print("Answer:")
arr_to_split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_parts = np.split(arr_to_split, 3)
print(f"Original array: {arr_to_split}")
for i, part in enumerate(split_parts):
    print(f"Part {i+1}: {part}")



Q17.1: Split an array into 3 equal parts using np.split()
Answer:
Original array: [1 2 3 4 5 6 7 8 9]
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]


In [1403]:

print("\nQ17.2: Split an array at specific indices using np.split()")
print("Answer:")
split_at_indices = np.split(arr_to_split, [3, 6])
print(f"Split at indices [3, 6]:")
for i, part in enumerate(split_at_indices):
    print(f"Part {i+1}: {part}")



Q17.2: Split an array at specific indices using np.split()
Answer:
Split at indices [3, 6]:
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]


In [1404]:

print("\nQ17.3: Split an array horizontally using np.hsplit()")
print("Answer:")
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
print(f"Original 2D array:\n{arr_2d}")
for i, part in enumerate(hsplit_parts):
    print(f"Horizontal part {i+1}:\n{part}")



Q17.3: Split an array horizontally using np.hsplit()
Answer:
Original 2D array:
[[1 2 3]
 [4 5 6]]
Horizontal part 1:
[[1]
 [4]]
Horizontal part 2:
[[2]
 [5]]
Horizontal part 3:
[[3]
 [6]]


In [1405]:

print("\nQ17.4: Split an array vertically using np.vsplit()")
print("Answer:")
vsplit_parts = np.vsplit(arr_2d, 2)
print(f"Vertical parts:")
for i, part in enumerate(vsplit_parts):
    print(f"Part {i+1}:\n{part}")



Q17.4: Split an array vertically using np.vsplit()
Answer:
Vertical parts:
Part 1:
[[1 2 3]]
Part 2:
[[4 5 6]]


In [1406]:

print("\nQ17.5: Split an array into equal chunks using np.array_split()")
print("Answer:")
chunks = np.array_split(arr_to_split, 4)
print(f"Split into 4 chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}: {chunk}")



Q17.5: Split an array into equal chunks using np.array_split()
Answer:
Split into 4 chunks:
Chunk 1: [1 2 3]
Chunk 2: [4 5]
Chunk 3: [6 7]
Chunk 4: [8 9]


#### QUESTION 18: ARRAY REPETITION AND TILING

In [1407]:

print("\nQ18.1: Repeat each element of an array 3 times using np.repeat()")
print("Answer:")
repeat_elements = np.repeat(arr1, 3)
print(f"Original: {arr1}")
print(f"Repeated 3 times: {repeat_elements}")



Q18.1: Repeat each element of an array 3 times using np.repeat()
Answer:
Original: [1 2 3]
Repeated 3 times: [1 1 1 2 2 2 3 3 3]


In [1408]:

print("\nQ18.2: Repeat an entire array 2 times using np.tile()")
print("Answer:")
tiled_array = np.tile(arr1, 2)
print(f"Original: {arr1}")
print(f"Tiled 2 times: {tiled_array}")



Q18.2: Repeat an entire array 2 times using np.tile()
Answer:
Original: [1 2 3]
Tiled 2 times: [1 2 3 1 2 3]


In [1409]:

print("\nQ18.3: Repeat a 2D array using np.tile()")
print("Answer:")
arr_2d_small = np.array([[1, 2], [3, 4]])
tiled_2d = np.tile(arr_2d_small, (2, 3))
print(f"Original:\n{arr_2d_small}")
print(f"Tiled (2, 3):\n{tiled_2d}")



Q18.3: Repeat a 2D array using np.tile()
Answer:
Original:
[[1 2]
 [3 4]]
Tiled (2, 3):
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [1410]:

print("\nQ18.4: Create a pattern using np.tile()")
print("Answer:")
pattern = np.array([1, 0])
pattern_tiled = np.tile(pattern, 5)
print(f"Pattern: {pattern}")
print(f"Tiled 5 times: {pattern_tiled}")



Q18.4: Create a pattern using np.tile()
Answer:
Pattern: [1 0]
Tiled 5 times: [1 0 1 0 1 0 1 0 1 0]


In [1411]:

print("\nQ18.5: Repeat elements with different counts using np.repeat()")
print("Answer:")
repeat_counts = [2, 1, 3]
repeated_variable = np.repeat(arr1, repeat_counts)
print(f"Original: {arr1}")
print(f"Repeat counts: {repeat_counts}")
print(f"Result: {repeated_variable}")


Q18.5: Repeat elements with different counts using np.repeat()
Answer:
Original: [1 2 3]
Repeat counts: [2, 1, 3]
Result: [1 1 2 3 3 3]


#### QUESTION 19: ARRAY COMPARISON AND LOGICAL OPERATIONS

In [1412]:

print("\nQ19.1: Compare two arrays for equality using np.array_equal()")
print("Answer:")
arr_a = np.array([1, 2, 3])
arr_b = np.array([1, 2, 3])
arr_c = np.array([1, 2, 4])
print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Array C: {arr_c}")
print(f"A equals B: {np.array_equal(arr_a, arr_b)}")
print(f"A equals C: {np.array_equal(arr_a, arr_c)}")



Q19.1: Compare two arrays for equality using np.array_equal()
Answer:
Array A: [1 2 3]
Array B: [1 2 3]
Array C: [1 2 4]
A equals B: True
A equals C: False


In [1413]:

print("\nQ19.2: Check if arrays are close using np.allclose()")
print("Answer:")
arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(f"Array D: {arr_d}")
print(f"Array E: {arr_e}")
print(f"Arrays are close: {np.allclose(arr_d, arr_e, atol=0.01)}")



Q19.2: Check if arrays are close using np.allclose()
Answer:
Array D: [1. 2. 3.]
Array E: [1.001 2.001 3.001]
Arrays are close: True


In [1414]:

print("\nQ19.3: Apply logical AND operation between arrays")
print("Answer:")
logical_and = np.logical_and(arr_a > 1, arr_a < 3)
print(f"Array: {arr_a}")
print(f"Logical AND (1 < x < 3): {logical_and}")



Q19.3: Apply logical AND operation between arrays
Answer:
Array: [1 2 3]
Logical AND (1 < x < 3): [False  True False]


In [1415]:

print("\nQ19.4: Apply logical OR operation between arrays")
print("Answer:")
logical_or = np.logical_or(arr_a == 1, arr_a == 3)
print(f"Array: {arr_a}")
print(f"Logical OR (x == 1 OR x == 3): {logical_or}")



Q19.4: Apply logical OR operation between arrays
Answer:
Array: [1 2 3]
Logical OR (x == 1 OR x == 3): [ True False  True]


In [1416]:

print("\nQ19.5: Apply logical NOT operation to an array")
print("Answer:")
logical_not = np.logical_not(arr_a == 2)
print(f"Array: {arr_a}")
print(f"Logical NOT (x != 2): {logical_not}")



Q19.5: Apply logical NOT operation to an array
Answer:
Array: [1 2 3]
Logical NOT (x != 2): [ True False  True]


### QUESTION 20: ARRAY SET OPERATIONS

In [1417]:

print("\nQ20.1: Find unique elements in an array using np.unique()")
print("Answer:")
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
unique_elements = np.unique(arr_with_duplicates)
print(f"Original array: {arr_with_duplicates}")
print(f"Unique elements: {unique_elements}")



Q20.1: Find unique elements in an array using np.unique()
Answer:
Original array: [1 2 2 3 3 3 4]
Unique elements: [1 2 3 4]


In [1418]:

print("\nQ20.2: Find the intersection of two arrays using np.intersect1d()")
print("Answer:")
arr_f = np.array([1, 2, 3, 4])
arr_g = np.array([3, 4, 5, 6])
intersection = np.intersect1d(arr_f, arr_g)
print(f"Array F: {arr_f}")
print(f"Array G: {arr_g}")
print(f"Intersection: {intersection}")



Q20.2: Find the intersection of two arrays using np.intersect1d()
Answer:
Array F: [1 2 3 4]
Array G: [3 4 5 6]
Intersection: [3 4]


In [1419]:

print("\nQ20.3: Find the union of two arrays using np.union1d()")
print("Answer:")
union = np.union1d(arr_f, arr_g)
print(f"Union: {union}")



Q20.3: Find the union of two arrays using np.union1d()
Answer:
Union: [1 2 3 4 5 6]


In [1420]:

print("\nQ20.4: Find elements in first array but not in second using np.setdiff1d()")
print("Answer:")
set_difference = np.setdiff1d(arr_f, arr_g)
print(f"Elements in F but not in G: {set_difference}")



Q20.4: Find elements in first array but not in second using np.setdiff1d()
Answer:
Elements in F but not in G: [1 2]


In [1421]:

print("\nQ20.5: Find the symmetric difference between two arrays using np.setxor1d()")
print("Answer:")
symmetric_diff = np.setxor1d(arr_f, arr_g)
print(f"Symmetric difference: {symmetric_diff}")


Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
Answer:
Symmetric difference: [1 2 5 6]


#### QUESTION 21: ARRAY SEARCHING AND COUNTING

In [1422]:

print("\nQ21.1: Count occurrences of a value using np.count_nonzero()")
print("Answer:")
arr_with_values = np.array([1, 2, 2, 3, 2, 4, 2])
count_of_2 = np.count_nonzero(arr_with_values == 2)
print(f"Array: {arr_with_values}")
print(f"Count of 2: {count_of_2}")



Q21.1: Count occurrences of a value using np.count_nonzero()
Answer:
Array: [1 2 2 3 2 4 2]
Count of 2: 4


In [1423]:

print("\nQ21.2: Find indices where a condition is True using np.where()")
print("Answer:")
indices_greater_than_2 = np.where(arr_with_values > 2)
print(f"Array: {arr_with_values}")
print(f"Indices where x > 2: {indices_greater_than_2[0]}")



Q21.2: Find indices where a condition is True using np.where()
Answer:
Array: [1 2 2 3 2 4 2]
Indices where x > 2: [3 5]


In [1424]:

print("\nQ21.3: Find the first index where a condition is True using np.argwhere()")
print("Answer:")
first_index_greater_than_2 = np.argwhere(arr_with_values > 2)[0][0]
print(f"First index where x > 2: {first_index_greater_than_2}")



Q21.3: Find the first index where a condition is True using np.argwhere()
Answer:
First index where x > 2: 3


In [1425]:

print("\nQ21.4: Check if any element satisfies a condition using np.any()")
print("Answer:")
any_greater_than_3 = np.any(arr_with_values > 3)
print(f"Array: {arr_with_values}")
print(f"Any element > 3: {any_greater_than_3}")



Q21.4: Check if any element satisfies a condition using np.any()
Answer:
Array: [1 2 2 3 2 4 2]
Any element > 3: True


In [1426]:

print("\nQ21.5: Check if all elements satisfy a condition using np.all()")
print("Answer:")
all_positive = np.all(arr_with_values > 0)
print(f"Array: {arr_with_values}")
print(f"All elements > 0: {all_positive}")


Q21.5: Check if all elements satisfy a condition using np.all()
Answer:
Array: [1 2 2 3 2 4 2]
All elements > 0: True


#### QUESTION 22: ARRAY BROADCASTING

In [1427]:

print("\nQ22.1: Demonstrate broadcasting with a scalar")
print("Answer:")
scalar = 5
broadcasted = arr_a + scalar
print(f"Array: {arr_a}")
print(f"Scalar: {scalar}")
print(f"Broadcasted result: {broadcasted}")



Q22.1: Demonstrate broadcasting with a scalar
Answer:
Array: [1 2 3]
Scalar: 5
Broadcasted result: [6 7 8]


In [1428]:

print("\nQ22.2: Demonstrate broadcasting with different shapes")
print("Answer:")
arr_2d_broadcast = np.array([[1], [2], [3]])
arr_1d_broadcast = np.array([10, 20])
broadcasted_2d = arr_2d_broadcast + arr_1d_broadcast
print(f"2D array:\n{arr_2d_broadcast}")
print(f"1D array: {arr_1d_broadcast}")
print(f"Broadcasted result:\n{broadcasted_2d}")



Q22.2: Demonstrate broadcasting with different shapes
Answer:
2D array:
[[1]
 [2]
 [3]]
1D array: [10 20]
Broadcasted result:
[[11 21]
 [12 22]
 [13 23]]


In [1429]:

print("\nQ22.3: Demonstrate broadcasting with np.newaxis")
print("Answer:")
arr_newaxis = arr_a[:, np.newaxis]
print(f"Original array: {arr_a}")
print(f"With newaxis:\n{arr_newaxis}")



Q22.3: Demonstrate broadcasting with np.newaxis
Answer:
Original array: [1 2 3]
With newaxis:
[[1]
 [2]
 [3]]


In [1430]:

print("\nQ22.4: Demonstrate broadcasting with np.outer()")
print("Answer:")
outer_product = np.outer(arr_a, arr_b)
print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Outer product:\n{outer_product}")



Q22.4: Demonstrate broadcasting with np.outer()
Answer:
Array A: [1 2 3]
Array B: [1 2 3]
Outer product:
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [1431]:

print("\nQ22.5: Demonstrate broadcasting with np.einsum()")
print("Answer:")
einsum_result = np.einsum('i,j->ij', arr_a, arr_b)
print(f"Einsum result:\n{einsum_result}")


Q22.5: Demonstrate broadcasting with np.einsum()
Answer:
Einsum result:
[[1 2 3]
 [2 4 6]
 [3 6 9]]


### QUESTION 23: ARRAY ITERATION AND INDEXING

In [1432]:

print("\nQ23.1: Iterate over array elements using np.nditer()")
print("Answer:")
print("Iterating over array elements:")
for element in np.nditer(arr_a):
    print(f"Element: {element}")



Q23.1: Iterate over array elements using np.nditer()
Answer:
Iterating over array elements:
Element: 1
Element: 2
Element: 3


In [1433]:

print("\nQ23.2: Iterate over array with index using np.ndenumerate()")
print("Answer:")
print("Iterating with indices:")
for index, element in np.ndenumerate(arr_a):
    print(f"Index {index}: {element}")



Q23.2: Iterate over array with index using np.ndenumerate()
Answer:
Iterating with indices:
Index (0,): 1
Index (1,): 2
Index (2,): 3


In [1434]:

print("\nQ23.3: Use advanced indexing with boolean arrays")
print("Answer:")
bool_mask = np.array([True, False, True])
advanced_indexed = arr_a[bool_mask]
print(f"Array: {arr_a}")
print(f"Boolean mask: {bool_mask}")
print(f"Advanced indexed result: {advanced_indexed}")



Q23.3: Use advanced indexing with boolean arrays
Answer:
Array: [1 2 3]
Boolean mask: [ True False  True]
Advanced indexed result: [1 3]


In [1435]:

print("\nQ23.4: Use integer array indexing")
print("Answer:")
int_indices = np.array([0, 2])
integer_indexed = arr_a[int_indices]
print(f"Array: {arr_a}")
print(f"Integer indices: {int_indices}")
print(f"Integer indexed result: {integer_indexed}")



Q23.4: Use integer array indexing
Answer:
Array: [1 2 3]
Integer indices: [0 2]
Integer indexed result: [1 3]


In [1436]:

print("\nQ23.5: Use fancy indexing with multiple arrays")
print("Answer:")
row_indices = np.array([0, 1])
col_indices = np.array([1, 2])
arr_2d_fancy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
fancy_indexed = arr_2d_fancy[row_indices, col_indices]
print(f"2D array:\n{arr_2d_fancy}")
print(f"Row indices: {row_indices}")
print(f"Column indices: {col_indices}")
print(f"Fancy indexed result: {fancy_indexed}")


Q23.5: Use fancy indexing with multiple arrays
Answer:
2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row indices: [0 1]
Column indices: [1 2]
Fancy indexed result: [2 6]


### QUESTION 24: ARRAY VIEWS AND COPIES

In [1437]:
print("\nQ24.1: Create a view of an array using slicing")
print("Answer:")
arr_original = np.array([1, 2, 3, 4, 5])
arr_view = arr_original[1:4]
print(f"Original array: {arr_original}")
print(f"View: {arr_view}")
print(f"Are they the same object? {arr_view is arr_original}")
print(f"Do they share memory? {arr_view.base is arr_original}")



Q24.1: Create a view of an array using slicing
Answer:
Original array: [1 2 3 4 5]
View: [2 3 4]
Are they the same object? False
Do they share memory? True


In [1438]:

print("\nQ24.2: Create a copy of an array using np.copy()")
print("Answer:")
arr_copy = np.copy(arr_original)
print(f"Original array: {arr_original}")
print(f"Copy: {arr_copy}")
print(f"Are they the same object? {arr_copy is arr_original}")
print(f"Do they share memory? {arr_copy.base is arr_original}")



Q24.2: Create a copy of an array using np.copy()
Answer:
Original array: [1 2 3 4 5]
Copy: [1 2 3 4 5]
Are they the same object? False
Do they share memory? False


In [1439]:

print("\nQ24.3: Demonstrate the difference between view and copy")
print("Answer:")
arr_original[0] = 99
print(f"After modifying original:")
print(f"Original: {arr_original}")
print(f"View: {arr_view}")
print(f"Copy: {arr_copy}")



Q24.3: Demonstrate the difference between view and copy
Answer:
After modifying original:
Original: [99  2  3  4  5]
View: [2 3 4]
Copy: [1 2 3 4 5]


In [1440]:

print("\nQ24.4: Create a view using np.view()")
print("Answer:")
arr_view_method = arr_original.view()
print(f"Original: {arr_original}")
print(f"View: {arr_view_method}")
print(f"Are they the same object? {arr_view_method is arr_original}")



Q24.4: Create a view using np.view()
Answer:
Original: [99  2  3  4  5]
View: [99  2  3  4  5]
Are they the same object? False


In [1441]:

print("\nQ24.5: Check if an array is a view or copy")
print("Answer:")
print(f"Original base: {arr_original.base}")
print(f"View base: {arr_view.base}")
print(f"Copy base: {arr_copy.base}")


Q24.5: Check if an array is a view or copy
Answer:
Original base: None
View base: [99  2  3  4  5]
Copy base: None


#### QUESTION 25: ARRAY MEMORY LAYOUT

In [1442]:
print("\nQ25.1: Check if an array is C-contiguous using np.flags")
print("Answer:")
print(f"Array flags:")
print(f"C-contiguous: {arr_a.flags.c_contiguous}")
print(f"F-contiguous: {arr_a.flags.f_contiguous}")



Q25.1: Check if an array is C-contiguous using np.flags
Answer:
Array flags:
C-contiguous: True
F-contiguous: True


In [1443]:

print("\nQ25.2: Check array memory layout using np.flags")
print("Answer:")
print(f"Memory layout flags:")
print(f"OWNDATA: {arr_a.flags.owndata}")
print(f"WRITEABLE: {arr_a.flags.writeable}")
print(f"ALIGNED: {arr_a.flags.aligned}")



Q25.2: Check array memory layout using np.flags
Answer:
Memory layout flags:
OWNDATA: True
WRITEABLE: True
ALIGNED: True


In [1444]:

print("\nQ25.3: Make an array C-contiguous using np.ascontiguousarray()")
print("Answer:")
arr_f_style = np.array([[1, 2], [3, 4]], order='F')
arr_c_style = np.ascontiguousarray(arr_f_style)
print(f"F-style array:\n{arr_f_style}")
print(f"C-style array:\n{arr_c_style}")
print(f"F-style C-contiguous: {arr_f_style.flags.c_contiguous}")
print(f"C-style C-contiguous: {arr_c_style.flags.c_contiguous}")



Q25.3: Make an array C-contiguous using np.ascontiguousarray()
Answer:
F-style array:
[[1 2]
 [3 4]]
C-style array:
[[1 2]
 [3 4]]
F-style C-contiguous: False
C-style C-contiguous: True


In [1445]:

print("\nQ25.4: Check array strides")
print("Answer:")
print(f"Array shape: {arr_a.shape}")
print(f"Array strides: {arr_a.strides}")
print(f"Array itemsize: {arr_a.itemsize}")



Q25.4: Check array strides
Answer:
Array shape: (3,)
Array strides: (8,)
Array itemsize: 8


In [1446]:

print("\nQ25.5: Reshape array without copying using np.reshape()")
print("Answer:")
reshaped_no_copy = arr_a.reshape(1, 3)
print(f"Original: {arr_a}")
print(f"Reshaped: {reshaped_no_copy}")
print(f"Share memory? {reshaped_no_copy.base is arr_a}")


Q25.5: Reshape array without copying using np.reshape()
Answer:
Original: [1 2 3]
Reshaped: [[1 2 3]]
Share memory? True


### QUESTION 26: ARRAY POLYNOMIAL OPERATIONS

In [1447]:

print("\nQ26.1: Create a polynomial from roots using np.poly()")
print("Answer:")
roots = np.array([1, 2, 3])
polynomial = np.poly(roots)
print(f"Roots: {roots}")
print(f"Polynomial coefficients: {polynomial}")



Q26.1: Create a polynomial from roots using np.poly()
Answer:
Roots: [1 2 3]
Polynomial coefficients: [ 1. -6. 11. -6.]


In [1448]:

print("\nQ26.2: Find roots of a polynomial using np.roots()")
print("Answer:")
coeffs = np.array([1, -6, 11, -6])
roots_found = np.roots(coeffs)
print(f"Coefficients: {coeffs}")
print(f"Roots: {roots_found}")



Q26.2: Find roots of a polynomial using np.roots()
Answer:
Coefficients: [ 1 -6 11 -6]
Roots: [3. 2. 1.]


In [1449]:

print("\nQ26.3: Evaluate a polynomial using np.polyval()")
print("Answer:")
x_values = np.array([0, 1, 2, 3])
poly_values = np.polyval(coeffs, x_values)
print(f"Coefficients: {coeffs}")
print(f"X values: {x_values}")
print(f"Polynomial values: {poly_values}")



Q26.3: Evaluate a polynomial using np.polyval()
Answer:
Coefficients: [ 1 -6 11 -6]
X values: [0 1 2 3]
Polynomial values: [-6  0  0  0]


In [1450]:

print("\nQ26.4: Add two polynomials using np.polyadd()")
print("Answer:")
poly1 = np.array([1, 2, 3])
poly2 = np.array([4, 5])
sum_poly = np.polyadd(poly1, poly2)
print(f"Polynomial 1: {poly1}")
print(f"Polynomial 2: {poly2}")
print(f"Sum: {sum_poly}")



Q26.4: Add two polynomials using np.polyadd()
Answer:
Polynomial 1: [1 2 3]
Polynomial 2: [4 5]
Sum: [1 6 8]


In [1451]:

print("\nQ26.5: Multiply two polynomials using np.polymul()")
print("Answer:")
product_poly = np.polymul(poly1, poly2)
print(f"Product: {product_poly}")


Q26.5: Multiply two polynomials using np.polymul()
Answer:
Product: [ 4 13 22 15]


### QUESTION 27: ARRAY FINANCIAL FUNCTIONS

print("\nQ27.1: Calculate future value using np.fv()")
print("Answer:")
rate = 0.05  # 5% interest rate
nper = 10    # 10 periods
pmt = -100   # Payment of $100
pv = -1000   # Present value of $1000
fv = npf.fv(rate, nper, pmt, pv)
print(f"Rate: {rate}, Periods: {nper}, Payment: {pmt}, PV: {pv}")
print(f"Future Value: ${fv:.2f}")



print("\nQ27.2: Calculate present value using np.pv()")
print("Answer:")
fv_value = 2000
pv_calculated = np.pv(rate, nper, pmt, fv_value)
print(f"Present Value: ${pv_calculated:.2f}")



print("\nQ27.3: Calculate payment amount using np.pmt()")
print("Answer:")
payment = np.pmt(rate, nper, pv, fv_value)
print(f"Payment amount: ${payment:.2f}")



print("\nQ27.4: Calculate number of periods using np.nper()")
print("Answer:")
periods = np.nper(rate, pmt, pv, fv_value)
print(f"Number of periods: {periods:.1f}")


print("\nQ27.5: Calculate interest rate using np.rate()")
print("Answer:")
interest_rate = np.rate(nper, pmt, pv, fv_value)
print(f"Interest rate: {interest_rate:.4f}")

### QUESTION 28: ARRAY DISCRETE FOURIER TRANSFORM

In [1452]:
print("\nQ28.1: Compute 1D FFT using np.fft.fft()")
print("Answer:")
signal = np.array([1, 2, 3, 4, 5, 6, 7, 8])
fft_result = np.fft.fft(signal)
print(f"Signal: {signal}")
print(f"FFT result (first 4 values): {fft_result[:4]}")



Q28.1: Compute 1D FFT using np.fft.fft()
Answer:
Signal: [1 2 3 4 5 6 7 8]
FFT result (first 4 values): [36.+0.j         -4.+9.65685425j -4.+4.j         -4.+1.65685425j]


In [1453]:
print("\nQ28.2: Compute inverse FFT using np.fft.ifft()")
print("Answer:")
ifft_result = np.fft.ifft(fft_result)
print(f"Inverse FFT result: {ifft_result.real}")






Q28.2: Compute inverse FFT using np.fft.ifft()
Answer:
Inverse FFT result: [1. 2. 3. 4. 5. 6. 7. 8.]


In [1454]:
print("\nQ28.3: Compute 2D FFT using np.fft.fft2()")
print("Answer:")
signal_2d = np.array([[1, 2], [3, 4]])
fft_2d = np.fft.fft2(signal_2d)
print(f"2D signal:\n{signal_2d}")
print(f"2D FFT:\n{fft_2d}")


Q28.3: Compute 2D FFT using np.fft.fft2()
Answer:
2D signal:
[[1 2]
 [3 4]]
2D FFT:
[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]]


In [1455]:
print("\nQ28.4: Compute FFT frequency bins using np.fft.fftfreq()")
print("Answer:")
freq_bins = np.fft.fftfreq(8)
print(f"Frequency bins: {freq_bins}")



Q28.4: Compute FFT frequency bins using np.fft.fftfreq()
Answer:
Frequency bins: [ 0.     0.125  0.25   0.375 -0.5   -0.375 -0.25  -0.125]


In [1456]:

print("\nQ28.5: Shift zero-frequency component to center using np.fft.fftshift()")
print("Answer:")
fft_shifted = np.fft.fftshift(fft_result)
print(f"Shifted FFT (first 4 values): {fft_shifted[:4]}")


Q28.5: Shift zero-frequency component to center using np.fft.fftshift()
Answer:
Shifted FFT (first 4 values): [-4.+0.j         -4.-1.65685425j -4.-4.j         -4.-9.65685425j]


##### QUESTION 29: ARRAY INTERPOLATION

In [1457]:

print("\nQ29.1: Linear interpolation using np.interp()")
print("Answer:")
x_known = np.array([0, 1, 2, 3, 4])
y_known = np.array([0, 1, 4, 9, 16])
x_new = np.array([0.5, 1.5, 2.5, 3.5])
y_interpolated = np.interp(x_new, x_known, y_known)
print(f"Known x: {x_known}")
print(f"Known y: {y_known}")
print(f"New x: {x_new}")
print(f"Interpolated y: {y_interpolated}")




Q29.1: Linear interpolation using np.interp()
Answer:
Known x: [0 1 2 3 4]
Known y: [ 0  1  4  9 16]
New x: [0.5 1.5 2.5 3.5]
Interpolated y: [ 0.5  2.5  6.5 12.5]


In [1458]:
print("\nQ29.2: Polynomial interpolation using np.polyfit() and np.polyval()")
print("Answer:")
coefficients = np.polyfit(x_known, y_known, 2)
y_poly = np.polyval(coefficients, x_new)
print(f"Polynomial coefficients: {coefficients}")
print(f"Polynomial interpolated y: {y_poly}")



Q29.2: Polynomial interpolation using np.polyfit() and np.polyval()
Answer:
Polynomial coefficients: [ 1.00000000e+00 -3.25661647e-15  5.48662426e-15]
Polynomial interpolated y: [ 0.25  2.25  6.25 12.25]


In [1459]:

print("\nQ29.3: 1D interpolation using scipy.interpolate (if available)")
print("Answer:")
try:
    from scipy import interpolate
    f = interpolate.interp1d(x_known, y_known, kind='cubic')
    y_cubic = f(x_new)
    print(f"Cubic interpolated y: {y_cubic}")
except ImportError:
    print("SciPy not available for cubic interpolation")



Q29.3: 1D interpolation using scipy.interpolate (if available)
Answer:
SciPy not available for cubic interpolation


In [1460]:

print("\nQ29.4: Interpolate missing values using np.interp()")
print("Answer:")
data_with_nan = np.array([1, np.nan, 3, np.nan, 5])
valid_indices = ~np.isnan(data_with_nan)
x_valid = np.arange(len(data_with_nan))[valid_indices]
y_valid = data_with_nan[valid_indices]
x_all = np.arange(len(data_with_nan))
interpolated_data = np.interp(x_all, x_valid, y_valid)
print(f"Original data: {data_with_nan}")
print(f"Interpolated data: {interpolated_data}")



Q29.4: Interpolate missing values using np.interp()
Answer:
Original data: [ 1. nan  3. nan  5.]
Interpolated data: [1. 2. 3. 4. 5.]


In [1461]:
print("\nQ29.5: 2D interpolation using np.meshgrid()")
print("Answer:")
x = np.array([0, 1, 2])
y = np.array([0, 1, 2])
z = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4]])
X, Y = np.meshgrid(x, y)
print(f"X meshgrid:\n{X}")
print(f"Y meshgrid:\n{Y}")
print(f"Z values:\n{z}")


Q29.5: 2D interpolation using np.meshgrid()
Answer:
X meshgrid:
[[0 1 2]
 [0 1 2]
 [0 1 2]]
Y meshgrid:
[[0 0 0]
 [1 1 1]
 [2 2 2]]
Z values:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


### QUESTION 30: ARRAY SIGNAL PROCESSING

In [1462]:
print("\nQ30.1: Create a sine wave signal")
print("Answer:")
t = np.linspace(0, 2*np.pi, 100)
sine_wave = np.sin(t)
print(f"Time points: {len(t)}")
print(f"Sine wave amplitude range: [{np.min(sine_wave):.3f}, {np.max(sine_wave):.3f}]")



Q30.1: Create a sine wave signal
Answer:
Time points: 100
Sine wave amplitude range: [-1.000, 1.000]


In [1463]:

print("\nQ30.2: Add noise to a signal")
print("Answer:")
noise = np.random.normal(0, 0.1, len(sine_wave))
noisy_signal = sine_wave + noise
print(f"Noise standard deviation: {np.std(noise):.3f}")
print(f"Signal-to-noise ratio: {np.std(sine_wave)/np.std(noise):.3f}")



Q30.2: Add noise to a signal
Answer:
Noise standard deviation: 0.103
Signal-to-noise ratio: 6.850


In [1464]:

print("\nQ30.3: Apply a moving average filter")
print("Answer:")
window_size = 5
moving_avg = np.convolve(noisy_signal, np.ones(window_size)/window_size, mode='valid')
print(f"Moving average window size: {window_size}")
print(f"Filtered signal length: {len(moving_avg)}")



Q30.3: Apply a moving average filter
Answer:
Moving average window size: 5
Filtered signal length: 96


In [1465]:

print("\nQ30.4: Create a window function (Hamming)")
print("Answer:")
hamming_window = np.hamming(20)
print(f"Hamming window (first 5 values): {hamming_window[:5]}")



Q30.4: Create a window function (Hamming)
Answer:
Hamming window (first 5 values): [0.08       0.10492407 0.17699537 0.28840385 0.42707668]


In [1466]:

print("\nQ30.5: Apply window function to signal")
print("Answer:")
windowed_signal = sine_wave[:20] * hamming_window
print(f"Windowed signal (first 5 values): {windowed_signal[:5]}")


Q30.5: Apply window function to signal
Answer:
Windowed signal (first 5 values): [0.         0.0066547  0.02240628 0.05458079 0.10725945]


### QUESTION 31: ARRAY OPTIMIZATION AND PERFORMANCE

In [1467]:

print("\nQ31.1: Time array operations using time module")
print("Answer:")
import time
large_array = np.random.random(1000000)
start_time = time.time()
result = np.sum(large_array)
end_time = time.time()
print(f"Array size: {len(large_array)}")
print(f"Sum: {result:.6f}")
print(f"Time taken: {(end_time - start_time)*1000:.3f} ms")



Q31.1: Time array operations using time module
Answer:
Array size: 1000000
Sum: 500341.613782
Time taken: 2.293 ms


In [1468]:

print("\nQ31.2: Compare vectorized vs loop operations")
print("Answer:")
small_array = np.random.random(1000)
# Vectorized operation
start_time = time.time()
vectorized_result = np.square(small_array)
vectorized_time = time.time() - start_time

# Loop operation
start_time = time.time()
loop_result = np.array([x**2 for x in small_array])
loop_time = time.time() - start_time

print(f"Vectorized time: {vectorized_time*1000:.3f} ms")
print(f"Loop time: {loop_time*1000:.3f} ms")
print(f"Speedup: {loop_time/vectorized_time:.1f}x")



Q31.2: Compare vectorized vs loop operations
Answer:
Vectorized time: 0.207 ms
Loop time: 0.908 ms
Speedup: 4.4x


In [1469]:
print("\nQ31.3: Use memory-efficient operations")
print("Answer:")
# In-place operation
arr_inplace = np.array([1, 2, 3, 4, 5])
arr_inplace *= 2
print(f"In-place multiplication: {arr_inplace}")



Q31.3: Use memory-efficient operations
Answer:
In-place multiplication: [ 2  4  6  8 10]


In [1470]:
print("\nQ31.4: Optimize array creation")
print("Answer:")
# Pre-allocate array
preallocated = np.zeros(1000)
for i in range(1000):
    preallocated[i] = i**2
print(f"Pre-allocated array sum: {np.sum(preallocated)}")



Q31.4: Optimize array creation
Answer:
Pre-allocated array sum: 332833500.0


In [1471]:
print("\nQ31.5: Use efficient array methods")
print("Answer:")
# Use built-in methods instead of Python loops
efficient_sum = large_array.sum()
efficient_mean = large_array.mean()
print(f"Efficient sum: {efficient_sum:.6f}")
print(f"Efficient mean: {efficient_mean:.6f}")


Q31.5: Use efficient array methods
Answer:
Efficient sum: 500341.613782
Efficient mean: 0.500342


### QUESTION 32: ARRAY MASKED ARRAYS

In [1472]:
print("\nQ32.1: Create a masked array with invalid values")
print("Answer:")
data_with_invalid = np.array([1, 2, -999, 4, 5])
mask = (data_with_invalid == -999)
masked_array = np.ma.masked_array(data_with_invalid, mask=mask)
print(f"Original data: {data_with_invalid}")
print(f"Mask: {mask}")
print(f"Masked array: {masked_array}")



Q32.1: Create a masked array with invalid values
Answer:
Original data: [   1    2 -999    4    5]
Mask: [False False  True False False]
Masked array: [1 2 -- 4 5]


In [1473]:

print("\nQ32.2: Calculate statistics on masked array")
print("Answer:")
masked_mean = np.ma.mean(masked_array)
masked_std = np.ma.std(masked_array)
print(f"Masked array mean: {masked_mean}")
print(f"Masked array std: {masked_std}")



Q32.2: Calculate statistics on masked array
Answer:
Masked array mean: 3.0
Masked array std: 1.5811388300841898


In [1474]:

print("\nQ32.3: Fill masked values with a specific value")
print("Answer:")
filled_array = masked_array.filled(fill_value=0)
print(f"Filled array: {filled_array}")



Q32.3: Fill masked values with a specific value
Answer:
Filled array: [1 2 0 4 5]


In [1475]:
print("\nQ32.4: Create masked array from condition")
print("Answer:")
condition_mask = (data_with_invalid < 0)
conditioned_masked = np.ma.masked_array(data_with_invalid, mask=condition_mask)
print(f"Condition mask: {condition_mask}")
print(f"Conditioned masked array: {conditioned_masked}")



Q32.4: Create masked array from condition
Answer:
Condition mask: [False False  True False False]
Conditioned masked array: [1 2 -- 4 5]


In [1476]:
print("\nQ32.5: Combine multiple masks")
print("Answer:")
mask1 = (data_with_invalid < 0)
mask2 = (data_with_invalid > 10)
combined_mask = mask1 | mask2
combined_masked = np.ma.masked_array(data_with_invalid, mask=combined_mask)
print(f"Combined mask: {combined_mask}")
print(f"Combined masked array: {combined_masked}")


Q32.5: Combine multiple masks
Answer:
Combined mask: [False False  True False False]
Combined masked array: [1 2 -- 4 5]


### QUESTION 33: ARRAY STRUCTURED ARRAYS

In [1477]:
print("\nQ33.1: Create a structured array with named fields")
print("Answer:")
dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]
structured_data = np.array([('Alice', 25, 165.5), ('Bob', 30, 180.0)], dtype=dtype)
print(f"Structured array:\n{structured_data}")



Q33.1: Create a structured array with named fields
Answer:
Structured array:
[('Alice', 25, 165.5) ('Bob', 30, 180. )]


In [1478]:

print("\nQ33.2: Access structured array fields")
print("Answer:")
names = structured_data['name']
ages = structured_data['age']
print(f"Names: {names}")
print(f"Ages: {ages}")



Q33.2: Access structured array fields
Answer:
Names: ['Alice' 'Bob']
Ages: [25 30]


In [1479]:

print("\nQ33.3: Sort structured array by field")
print("Answer:")
sorted_by_age = np.sort(structured_data, order='age')
print(f"Sorted by age:\n{sorted_by_age}")



Q33.3: Sort structured array by field
Answer:
Sorted by age:
[('Alice', 25, 165.5) ('Bob', 30, 180. )]


In [1480]:

print("\nQ33.4: Filter structured array by condition")
print("Answer:")
tall_people = structured_data[structured_data['height'] > 170]
print(f"People taller than 170cm:\n{tall_people}")



Q33.4: Filter structured array by condition
Answer:
People taller than 170cm:
[('Bob', 30, 180.)]


In [1481]:

print("\nQ33.5: Create structured array from existing arrays")
print("Answer:")
names_array = np.array(['Charlie', 'Diana'])
ages_array = np.array([35, 28])
heights_array = np.array([175.0, 162.0])
new_structured = np.core.records.fromarrays([names_array, ages_array, heights_array], 
                                           names='name,age,height')
print(f"New structured array:\n{new_structured}")


Q33.5: Create structured array from existing arrays
Answer:
New structured array:
[('Charlie', 35, 175.) ('Diana', 28, 162.)]


C:\Users\DELL\AppData\Local\Temp\ipykernel_1196\2360368372.py:6: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  new_structured = np.core.records.fromarrays([names_array, ages_array, heights_array],


##### QUESTION 34: ARRAY RECORD ARRAYS

In [1482]:
print("\nQ34.1: Create a record array")
print("Answer:")
record_array = np.rec.array([('Eve', 22, 160.0), ('Frank', 45, 175.0)], 
                           dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
print(f"Record array:\n{record_array}")



Q34.1: Create a record array
Answer:
Record array:
[('Eve', 22, 160.) ('Frank', 45, 175.)]


In [1483]:

print("\nQ34.2: Access record array attributes")
print("Answer:")
print(f"First person name: {record_array[0].name}")
print(f"First person age: {record_array[0].age}")



Q34.2: Access record array attributes
Answer:
First person name: Eve
First person age: 22


In [1484]:

print("\nQ34.3: Filter record array by attribute")
print("Answer:")
young_people = record_array[record_array.age < 30]
print(f"Young people:\n{young_people}")



Q34.3: Filter record array by attribute
Answer:
Young people:
[('Eve', 22, 160.)]


In [1485]:

print("\nQ34.4: Sort record array by multiple fields")
print("Answer:")
sorted_records = np.sort(record_array, order=['age', 'height'])
print(f"Sorted by age then height:\n{sorted_records}")



Q34.4: Sort record array by multiple fields
Answer:
Sorted by age then height:
[('Eve', 22, 160.) ('Frank', 45, 175.)]


In [1486]:

print("\nQ34.5: Convert record array to regular array")
print("Answer:")
regular_array = np.array(record_array.tolist())
print(f"Regular array:\n{regular_array}")



Q34.5: Convert record array to regular array
Answer:
Regular array:
[['Eve' '22' '160.0']
 ['Frank' '45' '175.0']]


#### QUESTION 35: ARRAY UNIVERSAL FUNCTIONS (UFUNCS)

In [1487]:
print("\nKey Statistics Summary:")
print(f"Total Revenue: ${np.sum(retail_data[:, 1] * retail_data[:, 2]):.2f}")
print(f"Average Price: ${np.mean(retail_data[:, 1]):.2f}")
print(f"Total Products Sold: {np.sum(retail_data[:, 2])}")
print(f"Average Customer Rating: {np.mean(retail_data[:, 3]):.2f}")
print(f"Average Days in Stock: {np.mean(retail_data[:, 4]):.1f}")

print("\nTop Performing Products:")
# Sort by revenue (price × quantity)
revenue = retail_data[:, 1] * retail_data[:, 2]
top_products_idx = np.argsort(revenue)[-3:][::-1]
for i, idx in enumerate(top_products_idx):
    product = retail_data[idx]
    revenue_val = product[1] * product[2]
    print(f"{i+1}. Product {product[0]}: ${revenue_val:.2f}")



Key Statistics Summary:
Total Revenue: $16527.35
Average Price: $48.19
Total Products Sold: 465.0
Average Customer Rating: 4.25
Average Days in Stock: 13.3

Top Performing Products:
1. Product 1007.0: $2239.44
2. Product 1010.0: $2039.66
3. Product 1006.0: $1959.72
