In [4]:
import numpy as np
np.random.randint(0, 100, 1)

array([63], dtype=int32)

In [6]:
import numpy as np
np.random.randint(0,100,5)

array([27, 87, 25, 70, 20], dtype=int32)

In [ ]:
import numpy as np 
np.random.seed(111)
data = np.random.randint(0,100,(5,5))

array([[63, 15, 16, 95, 40],
       [13, 93, 47, 49,  3],
       [15, 65, 71, 25, 11],
       [40, 89,  5, 90, 92],
       [97, 19,  6, 63,  3]], dtype=int32)

In [10]:
np.random.randint(0,100,(2,2,3))

array([[[23, 37, 71],
        [76, 77,  1]],

       [[54, 21, 20],
        [26, 76, 16]]], dtype=int32)

In [15]:
np.random.randint(0,100,(2,1,3))

array([[[75, 68, 68]],

       [[11, 16, 97]]], dtype=int32)

In [20]:
np.random.rand(3,3)

array([[0.65674852, 0.01320325, 0.47381739],
       [0.93922443, 0.58491469, 0.27624501],
       [0.53494272, 0.89396411, 0.12206364]])

In [2]:
import numpy as np
data = np.random.randint(0,100)
data

87

In [11]:
import numpy as np
data = np.random.randint(0,100,(4,4))
data

array([[43, 74,  7, 73],
       [56,  8, 97, 70],
       [ 2, 44, 84, 21],
       [30, 41, 38, 29]], dtype=int32)

In [13]:
data.reshape(8,2)

array([[43, 74],
       [ 7, 73],
       [56,  8],
       [97, 70],
       [ 2, 44],
       [84, 21],
       [30, 41],
       [38, 29]], dtype=int32)

In [14]:
data.ravel()

array([43, 74,  7, 73, 56,  8, 97, 70,  2, 44, 84, 21, 30, 41, 38, 29],
      dtype=int32)

In [ ]:
data.split(data,)

AttributeError: 'numpy.ndarray' object has no attribute 'split'

index based splitting
np.hsplit(data,[2,5])

In [20]:
data = np.random.randint(0,100,(2,4))
data

array([[82, 14, 73,  7],
       [40, 60, 19,  6]], dtype=int32)

In [21]:
np.vsplit(data,[1,3])

[array([[82, 14, 73,  7]], dtype=int32),
 array([[40, 60, 19,  6]], dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [22]:
np.vsplit(data,[1,2,3])

[array([[82, 14, 73,  7]], dtype=int32),
 array([[40, 60, 19,  6]], dtype=int32),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [25]:
data = np.random.randint(0,10,(20,4))


In [26]:
data

array([[9, 0, 0, 6],
       [4, 7, 1, 6],
       [5, 1, 6, 0],
       [4, 4, 8, 7],
       [6, 0, 8, 1],
       [7, 2, 7, 9],
       [8, 8, 9, 5],
       [1, 1, 9, 0],
       [5, 3, 9, 1],
       [7, 3, 4, 8],
       [2, 8, 3, 1],
       [4, 7, 9, 3],
       [3, 0, 6, 8],
       [6, 0, 1, 6],
       [9, 6, 7, 2],
       [2, 7, 6, 1],
       [7, 6, 0, 3],
       [7, 8, 7, 4],
       [4, 4, 1, 1],
       [1, 4, 0, 4]], dtype=int32)

In [27]:
np.hsplit(data,[1,2,3])

[array([[9],
        [4],
        [5],
        [4],
        [6],
        [7],
        [8],
        [1],
        [5],
        [7],
        [2],
        [4],
        [3],
        [6],
        [9],
        [2],
        [7],
        [7],
        [4],
        [1]], dtype=int32),
 array([[0],
        [7],
        [1],
        [4],
        [0],
        [2],
        [8],
        [1],
        [3],
        [3],
        [8],
        [7],
        [0],
        [0],
        [6],
        [7],
        [6],
        [8],
        [4],
        [4]], dtype=int32),
 array([[0],
        [1],
        [6],
        [8],
        [8],
        [7],
        [9],
        [9],
        [9],
        [4],
        [3],
        [9],
        [6],
        [1],
        [7],
        [6],
        [0],
        [7],
        [1],
        [0]], dtype=int32),
 array([[6],
        [6],
        [0],
        [7],
        [1],
        [9],
        [5],
        [0],
        [1],
        [8],
        [1],
        [3],
        [8],
      

In [28]:
np.vsplit(data,[1,2,3])

[array([[9, 0, 0, 6]], dtype=int32),
 array([[4, 7, 1, 6]], dtype=int32),
 array([[5, 1, 6, 0]], dtype=int32),
 array([[4, 4, 8, 7],
        [6, 0, 8, 1],
        [7, 2, 7, 9],
        [8, 8, 9, 5],
        [1, 1, 9, 0],
        [5, 3, 9, 1],
        [7, 3, 4, 8],
        [2, 8, 3, 1],
        [4, 7, 9, 3],
        [3, 0, 6, 8],
        [6, 0, 1, 6],
        [9, 6, 7, 2],
        [2, 7, 6, 1],
        [7, 6, 0, 3],
        [7, 8, 7, 4],
        [4, 4, 1, 1],
        [1, 4, 0, 4]], dtype=int32)]

In [ ]:
# vsplit, equalsplits
np.vsplit(data,2)

[array([[9, 0, 0, 6],
        [4, 7, 1, 6],
        [5, 1, 6, 0],
        [4, 4, 8, 7],
        [6, 0, 8, 1],
        [7, 2, 7, 9],
        [8, 8, 9, 5],
        [1, 1, 9, 0],
        [5, 3, 9, 1],
        [7, 3, 4, 8]], dtype=int32),
 array([[2, 8, 3, 1],
        [4, 7, 9, 3],
        [3, 0, 6, 8],
        [6, 0, 1, 6],
        [9, 6, 7, 2],
        [2, 7, 6, 1],
        [7, 6, 0, 3],
        [7, 8, 7, 4],
        [4, 4, 1, 1],
        [1, 4, 0, 4]], dtype=int32)]

In [ ]:
# hsplit, equal splits
np.hsplit(data,2)

[array([[9, 0],
        [4, 7],
        [5, 1],
        [4, 4],
        [6, 0],
        [7, 2],
        [8, 8],
        [1, 1],
        [5, 3],
        [7, 3],
        [2, 8],
        [4, 7],
        [3, 0],
        [6, 0],
        [9, 6],
        [2, 7],
        [7, 6],
        [7, 8],
        [4, 4],
        [1, 4]], dtype=int32),
 array([[0, 6],
        [1, 6],
        [6, 0],
        [8, 7],
        [8, 1],
        [7, 9],
        [9, 5],
        [9, 0],
        [9, 1],
        [4, 8],
        [3, 1],
        [9, 3],
        [6, 8],
        [1, 6],
        [7, 2],
        [6, 1],
        [0, 3],
        [7, 4],
        [1, 1],
        [0, 4]], dtype=int32)]

In [36]:
ldata =np.random.randint(0,10,(2,4))

In [38]:
ldata

array([[1, 0, 6, 2],
       [4, 7, 0, 8]], dtype=int32)

In [39]:
np.vsplit(ldata,[1,2])

[array([[1, 0, 6, 2]], dtype=int32),
 array([[4, 7, 0, 8]], dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [41]:
np.vsplit(ldata,2)

[array([[1, 0, 6, 2]], dtype=int32), array([[4, 7, 0, 8]], dtype=int32)]

In [1]:
def merge_count(arr):
    if len(arr) <= 1:
        return arr, 0

    mid = len(arr)//2
    left, inv_left = merge_count(arr[:mid])
    right, inv_right = merge_count(arr[mid:])

    merged = []
    i = j = inv = 0

    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            merged.append(left[i])
            i += 1
        else:
            merged.append(right[j])
            inv += len(left) - i
            j += 1

    merged.extend(left[i:])
    merged.extend(right[j:])

    return merged, inv + inv_left + inv_right


T = int(input())

for _ in range(T):
    N = int(input())
    arr = list(map(int, input().split()))

    _, swaps = merge_count(arr)

    print(swaps)

0


In [8]:
T = int(input())

T = int(input())

for _ in range(T):
    N = int(input())
    arr = list(map(int, input().split()))
    
    swaps = 0
    
    for i in range(len(arr)):
        for j in range(i+1, len(arr)):
            if arr[i] > arr[j]:
                swaps += 1
                
    print(swaps)

0
0
0


In [9]:
T = int(input())

for _ in range(T):
    N = int(input())
    arr = list(map(int, input().split()))
    
    swaps = 0
    
    for i in range(len(arr)):
        for j in range(i+1, len(arr)):
            if arr[i] > arr[j]:
                swaps += 1
                
    print(swaps)

0


In [10]:
T = int(input())

for _ in range(T):
    N = int(input())
    arr = list(map(int, input().split()))
    
    swaps = 0
    
    for i in range(len(arr)):
        for j in range(i+1, len(arr)):
            if arr[i] > arr[j]:
                swaps += 1
                
    print(swaps)

2
